cmd/regctl/root.go, docs/README.md
This helps with anyone embedding this that wants to send logs to Elastic/Splunk.
=> Adding support for json log output

cmd/regctl/image.go, regclient/manifest.go
Provides a CLI to view the current rate limit using an HTTP HEAD request which will not deduct from the current rate limit.
=> Adding image ratelimit CLI

.github/workflows/docker.yml, .github/workflows/go.yml, Makefile, README.md, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit, build/build-artifacts.sh, cmd/regsync/config.go, cmd/regsync/error.go, cmd/regsync/main.go, cmd/regsync/root.go, cmd/regsync/template.go, docs/README.md, go.mod, go.sum
regsync allows mirroring between registries based on a configuration file.
=> Adding regsync

regclient/regclient.go
When importing multiple host config entries, the for/range loop was reusing the same memory reference for the host config entries, leading to corruption. This references the entries with a new object in the loop.
=> Fixing host config corruption bug

cmd/regsync/root.go
This prevents a platform lookup from using the rate limit quota on Docker Hub on a server. The manifest list is only pulled to lookup the platform specific digest when the manifest list digest changes.
=> Cache regsync manifest get responses for manifest list

cmd/regsync/config.go, docs/README.md
- This also adds template support to regcert in the regsync config
=> Documenting regsync and new regctl features

pkg/auth/auth.go
This supports registries who's auth challenge is missing these fields.
=> Allow auth without service and scope challenge

cmd/regbot/main.go, cmd/regbot/root.go, cmd/regctl/main.go, cmd/regctl/root.go, cmd/regsync/main.go, cmd/regsync/root.go, pkg/retryable/error.go, pkg/retryable/retryable.go, pkg/wraperr/error.go, regclient/blob.go, regclient/error.go, regclient/image.go, regclient/manifest.go, regclient/repo.go, regclient/tag.go
=> Refactoring error handling and wrapping errors

regclient/ref.go, regclient/regclient.go
=> Move ref to separate file, disable logging by default

docs/README.md, docs/examples/regbot.yml, docs/examples/regsync.yml
Add a FAQ on GC, add examples for regsync and regbot
=> Add a FAQ on GC, add examples for regsync and regbot

.github/workflows/docker.yml
=> Fixing LD_FLAGS in docker image build

cmd/regbot/config.go, cmd/regbot/root.go, cmd/regctl/config.go, cmd/regctl/registry.go, cmd/regctl/root.go, cmd/regsync/config.go, cmd/regsync/root.go, docs/README.md, pkg/auth/auth.go, regclient/config.go, regclient/manifest.go, regclient/regclient.go, regclient/tag.go
Experimental support to delete tags from Docker Hub.
=> Adding Docker Hub tag delete

cmd/regctl/registry.go, go.mod, go.sum
=> Update interactive password call for windows

build/build-artifacts.sh, cmd/regctl/registry.go
=> Fixing build issue with regctl on Windows

.github/workflows/docker.yml, .github/workflows/go.yml
=> Skip GHA on forks

cmd/regbot/lua/README.md
This fixes the regbot docker image build errors.
=> Include placeholder for cmd/regbot/lua folder

pkg/auth/auth.go
=> Renew auth token shortly before expiration

Makefile, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
=> Fixing multi-platform docker builds

cmd/regbot/sandbox/image.go, docs/regbot.md
=> Adding import/export to regbot

cmd/regsync/root.go, docs/regsync.md
=> Adding regsync "registry" option

go.mod, go.sum, pkg/retryable/retryable.go, regclient/blob.go, regclient/blob/reader.go, regclient/blob_test.go, regclient/regclient.go, regclient/regclient_test.go
This includes retry methods on blob get and put requests. Testing of blob API's has also been added. This may help with #69 .
=> Adding blob get/put retry capability

.github/workflows/go.yml, Makefile
This adds build artifacts for platforms that are already supported in the multi-platform images.
=> Adding ppc64le and s390x artifacts

regclient/blob_test.go
Ending on a full blob before missed an "unexpected EOF" error seen with a partial final blob.
=> Add tests for partial final blob

regclient/blob.go
=> Accept a 201 on chunk upload for ECR

pkg/retryable/retryable.go, regclient/blob.go
=> Improve error handling, escape query args

.github/workflows/docker.yml
=> Fix GHA caching, push to GHCR

.github/workflows/docker.yml
=> Fix GHCR login

.github/workflows/docker.yml
=> GHA docker build caching

.github/workflows/docker.yml, .github/workflows/go.yml, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
=> Update to go 1.16, adjust caching

.github/workflows/docker.yml
=> Adjust buildkit caching in GHA to use ghcr

Makefile, docs/README.md, docs/examples/k8s-regsync.yaml
- Makefile only runs commands for vars once
- Example for k8s with regsync
- Readme fixes time template
=> Miscellaneous cleanup

.github/workflows/go.yml, Makefile
=> Adding support for darwin-arm64 (Mac M1)

.github/workflows/docker.yml
=> Fixing GHA in forks

cmd/regctl/artifact.go, pkg/archive/tar.go
If a directory is input rather than a file, package it as a tgz blob.
=> Support creating an artifact from a directory

cmd/regctl/artifact.go, pkg/archive/tar.go
This handles artifacts of directories packaged as a tar+gzip, automatically extracting into the output directory.
=> Support extracting an artifact of a directory

.github/workflows/go.yml
=> Verify go fmt in GHA

.github/workflows/go.yml
=> Add go vet to CI

regclient/manifest/manifest.go, regclient/manifest/manifest_test.go
=> Validate manifest media type and digest

cmd/regctl/image.go, cmd/regctl/manifest.go, docs/regctl.md
=> Adding option to delete manifest by tag

.github/workflows/inactive-cleanup.yml
=> GHA to clean stale issues/pr

.github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/issue.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md
n/a
This is a new feature for github templates on issues and PR's. They were created from a collection of other examples of open source projects.
These will be visible after merging as templates to create an issue or PR.
n/a
=> Adding github templates for issues and PRs

CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md
n/a
This is documentation updates for contributor guidelines, code of conduct, and a security policy.
n/a
n/a
=> Adding contributor docs

.github/workflows/docker.yml
n/a
Minor bug fix to GHA workflows to avoid potential issues with variables in case spaces or other special characters ever appear.
GHA doesn't break. This was run here: <https://github.com/sudo-bmitch/regclient/runs/4450997574?check_suite_focus=true>
n/a
=> Cleanup quoting on GHA vars

cmd/regctl/artifact.go, cmd/regctl/blob.go, cmd/regctl/completion.go, cmd/regctl/config.go, cmd/regctl/image.go, cmd/regctl/manifest.go, cmd/regctl/registry.go, cmd/regctl/repo.go, cmd/regctl/root.go, cmd/regctl/tag.go
n/a
This updates regctl to use the refactored regclient package names.
=> Refactor regctl to remove legacy packages

cmd/regbot/config.go, cmd/regbot/root.go, cmd/regbot/sandbox/blob.go, cmd/regbot/sandbox/image.go, cmd/regbot/sandbox/manifest.go, cmd/regbot/sandbox/reference.go, cmd/regbot/sandbox/sandbox.go, cmd/regbot/sandbox/tag.go
This updates regbot to use the refactored regclient package names.
=> Refactor regbot to remove legacy packages

cmd/regsync/config.go, cmd/regsync/root.go
This updates regsync to use the refactored regclient package names.
=> Refactor regsync to remove legacy packages

regclient.go
Fixes #136 
Some docker configs are including the scheme in their hostname (`https://registry.example.com`). This removes the scheme, and uses the value to configure TLS settings.
Configure the `~/.docker/config.json` with either `http://` or `https://` in front of the registry name in the auth section.
Fix handling of docker logins where scheme is included in the hostname
Testing this was manual, an automated test would need the filesystem to be swapped out, which may be easier in a later release. There's also a desire to implement the docker calls directly to reduce external dependencies.
=> Handle docker config hosts with a scheme

.github/workflows/go.yml, Makefile
This adds linting to the Makefile and GHA builds to avoid repeating some past mistakes.
Write bad code, and run `make lint`.
No docs since this isn't a user facing change.
=> Add linting checks to make and GHA

README.md, docs/README.md, docs/regctl.md
Docs were needed for the ocidir scheme, and I realized a few other bits needed to be cleaned or updated.
No code changes in this one.
=> Updating documentation for ocidir

internal/auth/auth.go
closes #153
Signed-off-by: David Schumann <davidgiga1993@gmail.com>
=> fix: refresh token not cleared when switching scopes

cmd/regsync/regsync_test.go, go.mod, go.sum, types/ref/ref.go, types/ref/ref_test.go
This removes the dependency on distribution/distribution by parsing refs locally.
All repository commands use a reference and should be unaffected by this change.
=> Removing external dependency for ref parsing

.github/PULL_REQUEST_TEMPLATE.md
Updating the PR template since not all changes require test or doc changes (like this one).
=> Not all PRs require test or doc changes

build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync.buildkit
The buildkit Dockerfiles don't rely on experimental features, change syntax tag to reflect GA features.
Build docker images with buildkit.
=> Buildkit syntax is no longer experimental

cmd/regctl/image.go, cmd/regctl/manifest.go
Include the `--format raw-body` option in the help text for `regctl`.
```
regctl manifest get --help
regctl image manifest --help
```
=> Document the raw-body format

.markdownlint.yml, CODE_OF_CONDUCT.md, Makefile, docs/README.md
This adds checks for markdown linting issues.
Violate a linter rule (like `*` instead of `-` for lists) and it should fail.
=> Add markdown linting

go.mod, go.sum
Routine bump of Go dependencies.
=> Bumping Go dependencies

internal/reghttp/http.go
The configuration for registry specific CAs was getting ignored. This detects the value and configures the custom CA's per registry with any configuration settings.
Use a self signed CA and either pass a `regcert` setting in the regsync/regbot yaml, or `regctl registry set -cacert ...`. 
Fix handling of registry CA configuration.
Similar to the previous registry TLS change, these settings are tested locally, but a public e2e test still needs to be added to the project.
=> Handle custom CA config for registries

internal/reghttp/http.go
This caches the the http client per remote host. This avoids recreating the TLS certificate chain per http request which wasn't very efficient.
Performance may improve.
=> Cache http client per host

build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync.buildkit
This uses the new `COPY --link` flag provided by buildkit. Details are in the [docker blog post](https://www.docker.com/blog/image-rebase-and-improved-remote-cache-support-in-new-buildkit/).
Docker builds with buildkit should continue to work, possibly faster.
=> Using buildkit COPY "link" flag

build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync.buildkit
Hopefully fixes the GHA build failures
When copying a directory in a Dockerfile, be explcit on the trailing `/`.
GHA for Docker should succeed.
=> Be explicit when copying directories

image.go
Image export to ocidir of a manifest list was including descriptors of child manifests in `image.json`.
Set the child option on manifest put during an image export of child manifests.
Image export to an ocidir should only include top level manifests in `index.json`.
Fix: image export of manifest list to ocidir should only define parent manifest in `index.json`
=> Set child field on manifest put in image export

docker-plugin/docker-regclient, docs/regbot-quickstart.md, docs/regsync-quickstart.md
Fixes #201
Updating scripts in quickstarts, and the docker CLI plugin, to remove tty when it's not needed.
=> Remove tty from docker run scripts

.github/workflows/docker.yml
Fixes broken GHA on cosign signing.
Sorry for the testing on main, that's the only place these images are built.
GHA should succeed after merge
=> Fixing image name for cosign in GHA

pkg/archive/compress.go
Adds a string method to CompressType
=> Add string method on CompressType

referrer.go, scheme/ocidir/referrer.go, scheme/ocidir/referrer_test.go, scheme/reg/manifest_test.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go, scheme/scheme.go, types/docker/schema2/manifest.go, types/oci/v1/manifest.go, types/referrer/referrer.go
This adds methods to the regclient for the [OCI wg-reference-types Proposal E](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_E.md). These API's are considered experimental until the proposal is converted into approved PR's to upstream OCI specs.
Adding experimental support for OCI referrers.
=> Adding referrer support

cmd/regctl/artifact.go
Adds the referrer APIs in regctl for artifact requests.
```
echo "test artifact" | regctl artifact put --refers registry.example.org/repo:v1 \
--annotation org.opencontainers.artifact.type=test \
--annotation org.example.greeting=hello \
--annotation org.example.location=world
regctl artifact list registry.example.org/repo:v1
```
Adds experimental referrer support to `regctl artifact` commands.
=> Adding referrers to regctl artifact CLI

blob_test.go, scheme/reg/blob.go, scheme/reg/blob_test.go
The `Content-Range` header passed an end value one byte too large.
The end value is set to the last byte sent, rather than the next start byte value.
Chunked uploaded will work with `distribution/distribution`'s main branch.
Fix for chunked uploads.
=> Fix Content-Range header

internal/rwfs/mem.go, internal/rwfs/os.go, internal/rwfs/rwfs.go, internal/rwfs/rwfs_test.go
This adds some methods to rwfs that will be useful for upcoming credhelper changes.
This is an internal only change.
=> Add Copy, Rename, and CreateTemp methods to rwfs

image.go
When importing a manifest list or index to an OCI Layout directory (`ocidir://`), multiple manifest entries are created. 
This fixes handling of child manifests in the image import process. The child flag was non-intuitive, so it's now passed directly to the handleManifest function instead of inferring it from the push flag.
`regctl image import ocidir://path file.tar` where `file.tar` contains a multi-platform image (which can be output from `docker buildx build`) no longer creates multiple manifest entries.
Fix image import from a multi-platform image to an `ocidir://` layout
=> Fix import to ocidir with manifest list or index

cmd/regbot/config.go, cmd/regbot/root.go, cmd/regsync/config.go, cmd/regsync/root.go, config/host.go, docs/regbot.md, docs/regsync.md
This adds support for credential helpers directly in regbot and regsync.
Use the `credHelper` field in their configuration files.
Support credential helpers directly in regsync and regbot.
=> Support for cred helper in regsync and regbot

cmd/regctl/artifact.go, internal/reqresp/reqresp.go, scheme/ocidir/referrer.go, scheme/ocidir/referrer_test.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go, scheme/scheme.go, types/descriptor.go, types/descriptor_test.go, types/oci/v1/artifact.go
This updates the refers experimental support for the [OCI WG Proposal E](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_E.md) that changed to a single tag instead of one per referrer.
```
regctl artifact put --refers $tgt
regctl artifact list $tgt
```
Updating refers support to current OCI WG design
Refers is still experimental, so documentation is not included.
=> Updating referrer to latest OCI WG design

mod/dag.go, mod/mod.go, mod/time.go, mod/time_test.go
For reproducible builds, support SOURCE_DATE_EPOC variable.
This only gets used when adding layers to an image in the mod methods.
=> Support source_date_epoc variable

.github/workflows/go.yml, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit, go.mod
Bump the Go version to 1.18.
Bump Go version to 1.18
=> Bump Go to 1.18

cmd/regctl/artifact.go, scheme/reg/referrer_test.go, types/oci/v1/artifact.go
The schema version is not being included in the proposed Artifact manifest.
Tests and documentation for experimental features are not included.
=> Delete schema from artifact manifest

types/oci/v1/config.go
This improves support for legacy features in Docker images.
Using a windows image with the ArgsEscape field defined:
```shell
regctl image config ...
```
=> Add the ArgsEscape field

cmd/regctl/image.go, docs/regctl.md, image.go, image_test.go, types/annotations.go, types/error.go, types/platform/platform.go, types/platform/platform_test.go
Adds a method to check the base image for changes.
```
regctl image check-base node --base debian:bullseye -v info
```
Feature: add `regctl image check-base`
=> Add image check-base

cmd/regctl/artifact.go
`regctl artifact put` with both a `--refers` and a tag was overwriting the refers reference rather than creating the tag.
Fix the creation of an artifact with both a refers and a tag.
```shell
echo hello | regctl artifact put --refers $some_image $artifact_name
```
Fix `regctl artifact put` with both a refers and a tag.
=> Fix artifact put with both refers and tag

image.go, image_test.go
Tests for check-base were updated to use the new test data.
Tests will pass
=> Update check-base tests

.github/workflows/docker.yml, .github/workflows/go.yml
This switches the GHA to use a matrix strategy for the docker image builds.
GHA won't fail and will have multiple concurrent jobs, one per image.
=> Update GHA for docker builds with matrix

Makefile
This updates the Makefile with help messages
```
$ make help
all                             Full build of Go binaries (including fmt, vet, test, and lint)
fmt                             go fmt
vet                             go vet
test                            go test
lint                            Run all linting
lint-go                         Run linting for Go
lint-md                         Run linting for markdown
vendor                          Vendor Go modules
binaries                        Build Go binaries
docker                          Build Docker images
test-docker                     Build multi-platform docker images (but do not tag)
artifacts                       Generate artifacts
```
Add help text to Makefile
=> Update Makefile with help text

.github/workflows/docker.yml
Fixes the broken GHA from #309
Fixes a bug in the GHA for mutating the image.
GHA build of docker images will hopefully succeed.
=> Fix ocidir reference in GHA

.github/workflows/docker.yml
GHA is failing since the output directory didn't exist.
Create the output directory before running the docker build in GHA.
GHA of the docker build won't fail after merging.
=> Create output directory for docker GHA build

.github/workflows/docker.yml
Creating the output directory didn't work before because the checkout ran after the mkdir.
Move checkout earlier in the GHA.
GHA of docker build should work.
=> Run the checkout before creating output dir

build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync.buildkit
This may be introducing permission and timestamp issues in parent folders. There are few scenarios where the alpine base image wouldn't need to be pulled, so there's little value add for this flag.
Alpine images will hopefully be reproducible.
=> Remove --link from buildkit builds

build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
This pins the versions of the ECR and GCR auth helpers included in the alpine images for reproducibility.
This should have no user visible impact.
=> Pin version of docker helpers in alpine images

build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
This adds:
- `CGO_ENABLED=0`
- `-trimpath`
- `-ldflags=-buildid=`
Alpine image builds should be reproducible.
=> Adding reproducible options to go install

.dockerignore, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
- Use curl instead of Git to pull lua mods.
- Use the vendor folder when available for Go builds
- Bump timestamps of copied files for reproducibility
Local builds may be faster after running `make vendor`. Reproducibility of regbot is improved.
=> Pull lua mods with curl, use vendor

internal/reghttp/http.go, scheme/reg/blob.go, scheme/reg/blob_test.go
May help with #323 
Responses on chunked uploads may include a range and new location on an error. This should be used for sending the next chunk.
Testing this requires networking failures.
Improve handling of network failures on blob push
=> Handle of blob patch error responses

cmd/regctl/registry.go, config/host.go, docs/regbot.md, docs/regsync.md, internal/reghttp/http.go, internal/reghttp/http_test.go
Related to #328
This adds configurable concurrency and request per second limits.
Configure regsync or regbot with creds like the following to limit requests to Docker Hub:
```yaml
creds:
- registry: localhost:5000
tls: disabled
- registry: docker.io
user: "{{env \"HUB_USER\"}}"
pass: "{{file \"/home/appuser/.docker/hub_token\"}}"
reqConcurrent: 2
reqPerSec: 20
```
With `regctl`, use:
```
regctl registry set --req-per-sec 20 docker.io
```
Add configurable limits on concurrency and requests per second.
This was manually tested to verify the requests per second worked. Further tests in the reghttp package should be added in the future.
=> Limit current requests and requests per second

.github/workflows/docker.yml
This removes a deprecated features in GHA and bumps versions on GHA steps.
Docker build should continue to work.
=> Update GHA, change set-output, bump versions

.version-bump.yml
This updates the syntax used by version-bump for filtering versions from sources.
```
make util-version-check
```
=> Update version bump for filter syntax

cmd/regctl/registry.go
Fixes #345 
Allows password to be read from stdin.
```
echo "secret" | regctl registry login --pass-stdin --user someuser test.example.org
```
`regctl registry login` supports reading the password from stdin
=> Allow password from stdin for regctl

mod/manifest.go
Manifests with an OCI manifest type, but non-OCI media types on descriptors were not converted to OCI with `regctl image mod --to-oci`.
This adjusts the OCI conversion process to convert everything and check for changes even on OCI types.
Converting the `ubuntu@sha256:f05532b6a1dec5f7a77a8d684af87bc9cd1f2b32eab301c109f8ad151b5565d1` image to OCI now works.
Converting to OCI now handles OCI manifests with mixed media types inside manifest.
=> Handle mixed manifests with image mod to-oci

cmd/regctl/blob.go, cmd/regctl/image.go, cmd/regctl/manifest.go, docs/regctl.md
Add `regctl manifest head` and `regctl blob head` commands to complement the `get` commands.
```
$ regctl manifest head localhost:5000/library/alpine
sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a
$ regctl manifest head localhost:5000/library/alpine --format headers
Content-Length: 1638
Content-Type: application/vnd.docker.distribution.manifest.list.v2+json
Date: Sun, 05 Feb 2023 21:57:16 GMT
Docker-Content-Digest: sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a"
X-Content-Type-Options: nosniff
$ regctl blob head localhost:5000/library/alpine …
```
=> Add regctl manifest/blob head commands

.github/workflows/docker.yml, .github/workflows/go.yml
Cosign v2 requires a `--yes` to prompts.
Pass additional flags to permit cosign signing.
GHA should not fail.
=> Approve cosign prompts

.github/workflows/docker.yml, .github/workflows/go.yml
The release action requires permissions that cannot be set on the PAT previously used for the releases.
Remove PAT and set permissions on the GHA job.
Next release should work.
=> Adjust GHA permissions for release action

.github/workflows/docker.yml
Fixes GHCR login.
Uses the built-in token rather than an external PAT.
GHA should complete the docker workflow after merge.
=> Using built in permissions for GHCR

.github/workflows/docker.yml
The beta token doesn't work for GHCR yet.
Revert to the classic token.
Docker workflow should succeed.
=> Reverting classic token for GHCR

.github/workflows/go.yml
The GHA update for the release action should not have deleted the token variable.
This adds the token variable back.
=> The token environment variable should still be set

cmd/regctl/image.go
This adds a `--platform` option `regctl image copy` and `regctl image export`.
```
regctl image copy --platform local busybox localhost:5000/library/busybox:local
```
- Add `--platform` option to `regctl image copy/export`
=> Add platform flag to regctl image copy and export

cmd/regctl/image.go, image.go
Fixes #377 
This adds the ability to name the image being exported for better integration with `docker load`.
```
regctl image export --platform local --name regclient/regctl:latest ocidir://output/regctl:scratch >regctl.tar
docker load <regctl.tar
```
Add option to override name in `regctl image export`
Unit tests were not included since this requires integration with `docker load`.
=> Add name for image export

cmd/regctl/blob.go
`regclient` already implements a method for mounting blobs between repositories in the same registry. This change exposes the method `BlobCopy` as `regctl blob copy`.
`regctl blob copy localhost:5000/foo/bar:latest localhost:5000/foo/baz:latest sha256:...`
=> Expose blob copy between repositories

cmd/regctl/blob.go, cmd/regctl/blob_test.go, docs/regctl.md
Adds some testing and docs to the `regctl blob copy` command.
=> Adding docs and testing for regctl blob copy

docker-plugin/docker-regclient, docs/examples/k8s-regsync.yaml, docs/examples/regsync.yml, docs/install.md, docs/regbot-quickstart.md, docs/regbot.md, docs/regctl.md, docs/regsync-quickstart.md, docs/regsync.md
This documents the `ghcr.io` image names.
=> Document ghcr.io image names

image.go, internal/reghttp/http.go, internal/reghttp/http_test.go, types/warning/warning.go, types/warning/warning_test.go
This adds support for the warning headers described by https://github.com/opencontainers/distribution-spec/pull/393
This requires a registry currently generating warning headers.
- Add support for registry warning headers
=> Add support for http warning messages

regclient.go
Add `WithRegOpts` func allow users to freely add `reg.Opt` elements.
Add `WithRegOpts` func.
=> add WithRegOpts

.github/workflows/vulncheck.yml, Makefile
This adds a weekly vulnerability scan using govulncheck.
```
make vulncheck-go
```
=> Add weekly govulncheck scan

blob.go, cmd/regbot/main.go, cmd/regbot/root.go, cmd/regctl/image.go, cmd/regctl/main.go, cmd/regctl/root.go, cmd/regsync/main.go, cmd/regsync/root.go, image.go, internal/asci/asci.go, internal/asci/asci_test.go, internal/asci/lines.go, internal/asci/lines_test.go, internal/asci/progress.go, internal/asci/progress_test.go, internal/units/size.go, internal/units/size_test.go, types/blob/reader.go
This is a start at #390. More work is needed to refactor the image copy to be aware of remaining blobs and add support for concurrent blob copies.
This adds a progress UI to the image copy showing each blob copy.
From a terminal:
```
regctl image copy $src $dst
```
Add progress display to `regctl image copy`
=> Add terminal progress during copy

internal/rwfs/rwfs.go
Two concurrent MkdirAll tasks can race, and a stat can return that the parent is missing and the mkdir on the parent can return file exists. That would result in the MkdirAll of the child to report that it exists.
This changes MkdirAll to not fail early if a mkdir responds that a parent folder exists.
Creating a new ocidir should not periodically fail trying to create a temp file.
Fix race when creating ocidir
=> Fix race in MkdirAll

internal/reqresp/reqresp.go
CI found a race in the reqresp package.
This adds a lock to prevent any races on the state.
GHA should succeed.
=> Fix race in reqresp mocking package

internal/godbg/godbg_other.go, internal/godbg/godbg_unix.go
Artifacts are failing to build on windows.
The syscall used in godbg is only available on Unix systems. This removes the debugging signal handler on windows binaries.
`make artifacts`
=> Fix artifact build for windows

.github/workflows/docker.yml
Reproducible builds would push the changing referrers on every build.
If the image is already pushed from a previous build, do not push it again.
Referrers should not be changed by nightly builds.
=> Skip push on a reproducible build

.github/workflows/docker.yml
Stderr redirect needs a space for parsing.
Fixed typo.
GHA should run without errors.
=> Fix stderr redirect in GHA

.github/workflows/docker.yml
I'm bad at debugging GHA shell scripts in my head.
Fixes the missing space before the closing `]`.
GHA will stop throwing errors.
=> GHA typo fix

README.md
The badges URL changed for GitHub workflows.
Use the new URL.
Badges will show green instead of red with a pointer to the badges github issue.
Fix GitHub badges.
=> Fix github workflow badges

.github/workflows/go.yml
Cache warnings are shown in GHA for Go.
Code is checkout before setting up Go so the go.sum file is available for caching.
GHA warnings will stop.
=> Checkout code before setting up Go for caching

cmd/regsync/regsync_test.go, cmd/regsync/root.go, docs/regsync.md
Regsync needs some performance and maintainability improvements.
Fixes #442
Refactoring regsync with the following changes:
- sync registry calls sync repo, which calls sync image
- support for syncing only the missing tags
- sync repo filters out target tags when missing option used
- tests now check other actions
```
regsync once -c regsync.yml --missing
```
Performance improvements for regsync
=> refactoring regsync

image.go
Symlinks in tar files were not properly handled.
Fixes #451.
This adds extra handling for symlinks encountered inside of a tar file.
1. Use buildkit to generate an image with duplicate layers (`WORKDIR /tmp; WORKDIR /` will create two identical empty layers).
2. Export the image with `docker save`.
3. Import it to a registry with `regctl image import`.
Handle symlinks in the tar file with `regctl image import`
=> Handle symlinks in tar from docker save

.github/workflows/version-check.yml
The version check was only supposed to run weekly.
Reschedule the version-bump in GHA.
GHA should only show the job running on Sunday morning (UTC).
=> Run the version check weekly

.github/workflows/go.yml, .github/workflows/vulncheck.yml
Go vulnerability check is flagging an old Go version used to build the binaries.
`actions/setup-go` caches the go version from previous builds and needs a flag to check if a new version has been released.
GHA vulnerability checks should not fail.
=> Ensure Go version is the latest

cmd/regctl/artifact.go, scheme/ocidir/referrer_test.go, scheme/scheme.go
This allows sorting of the referrers response by an annotation.
To order by creation date, newest first, and retrieve the most recent:
```
regctl artifact list --sort-annotation org.opencontainers.image.created --sort-desc $image
regctl artifact get --sort-annotation org.opencontainers.image.created --sort-desc --subject $image
```
Add ability to sort referrers by annotation.
=> Add sorting of referrers response

.github/workflows/version-check.yml, .github/workflows/vulncheck.yml
This gives the option to run the scheduled GHA jobs manually.
GHA will have an option to run the workflows after merging.
=> Allow scheduled workflows to be run on demand.

.github/workflows/ci-registry.yml, .gitignore, Makefile, build/ci-test.sh, build/zot-config.json
This adds some CI tests against registries.
```
make ci-distribution ci-zot
```
=> Add CI tests against registries

.github/release.sh
This adds a script used to generate releases.
```
./.github/release.sh -h
```
=> Add a release script

.github/release.sh
The release script contains a few bugs when running without dry-run.
This fixes the syntax script errors in the `release.sh` script.
=> Release script bug fixes

.github/workflows/docker.yml, build/oci-image.sh
`oci.opencontainers....` is the wrong annotation prefix.
`oci.opencontainers` -> `org.opencontainers`
```
regctl manifest get ghcr.io/regclient/regctl:alpine
```
Fix typo in OCI annotations
=> Fix typo in OCI annotation

.github/release.sh
Release script puts the wrong tag in the change log and doesn't sign the git tag.
Fix the changelog and add a `-s` to `git tag`.
=> Fix the changelog tag and sign the git tag

.version-bump.yml, Makefile
`DavidAnson/markdownlint` was always the upstream linter, but that project now provides a CLI in a Docker container directly.
```
make lint-md
```
=> Switch markdownlint CLI tool

types/ref/ref.go, types/ref/ref_test.go
This aligns the regexp for tags with the distribution-spec to make it clearer that this project aligns with the spec. The effect of the regexp is unchanged since `\w`  is the same as `[0-9A-Za-z_]`.
No impact.
=> Use the distribution-spec regexp for tags

scheme/reg/manifest.go
Accept headers should be pushed in order of preference.
Result should not be visible to users since registries should return the original manifest when possible.
=> Reorder manifest accept headers

.github/workflows/vulnscans.yml, .version-bump.yml, Makefile
This adds the OSV vulnerability scanner.
```
make osv-scanner
```
- Add OSV vulnerability scanner
=> Add OSV scanner

.github/workflows/docker.yml, build/oci-image.sh
Annotations do not contain the version number.
This adds the version as the `org.opencontainers.image.version` annotation.
```
regctl manifest get regclient/regctl:edge
```
- Include version annotation in regclient images
=> Add version as an annotation

cmd/regctl/artifact.go
This adds a `--latest` option to `regctl artifact get` and `regctl artifact list` to sort artifacts for the latest version of an artifact. This requires the `org.opencontainers.image.created` annotation to be defined on the artifact.
This also cleans up various flag options that do not have short versions flags to use the appropriate method.
```
$subject=localhost:5000/some/image:latest
echo "test1" | regctl artifact put --subject $subject \
--artifact-type application/org.example.demo \
--annotation org.opencontainers.image.created=2023-07-27T00:11:22Z
echo "test2" | regctl artifact put --subject $subject \
--artifact-type application/org.example.demo \
--annotation org.opencontainers.image.created=2023-07-28T00:11:22Z
regctl artifact list $subject \
--latest --filter-artifact-type …
```
=> Add latest flag to regctl artifact commands

.github/workflows/docker.yml, .github/workflows/go.yml, .version-bump.lock, Makefile, go.mod, go.sum
GHA is warning of stale dependencies.
Routine version update:
- go libraries
- cosign
- cosign installer
- syft
```shell
make util-golang-update util-version-update
```
=> Version bump

.github/PULL_REQUEST_TEMPLATE.md, Makefile
The unquoted `**/*.md` may get expanded by the shell (and in this case was getting expanded).
Quote the `"**/*.md"` so it gets processed by the linter, and then ignore the one error generated by the template.
```shell
make lint-md
```
=> Fix checking of markdown lint

blob.go, image.go, manifest.go, referrer.go, regclient.go, repo.go, scheme.go
A lot of the comments didn't render nicely in godoc.
Updating comments to be sentences and following formatting guides in <https://tip.golang.org/doc/comment>.
Rendered go docs will look better on the regclient package.
- Chore: Cleanup docs on regclient package.
=> Cleanup godoc comments on regclient package

Makefile
The default gosec output is a bit verbose.
Switch the output to terse mode.
```shell
make lint-gosec
```
=> Switch to terse output from gosec

internal/rwfs/rwfs_test.go, scheme/ocidir/ocidir_test.go, scheme/reg/reg_test.go, types/manifest/manifest_test.go
This adds a bit of basic testing around interface implementations. Based on https://go.dev/doc/faq#guarantee_satisfies_interface.
```shell
make test
```
=> Test for implementation of interfaces

mod/config.go, mod/layer.go, mod/manifest.go, mod/mod.go, regclient.go, scheme/scheme.go, types/blob/common.go, types/manifest/docker1.go, types/manifest/manifest.go, types/mediatype.go
This adds links to the replacement functions in the deprecation comments.
```
godoc -http localhost:6060
```
And then view comments for deprecated methods.
=> Cleanup links in "deprecated" comments

.github/workflows/go.yml
Set the `GOTOOLCHAIN=local` variable for CI testing. This avoids Go automatically upgrading to newer releases.
- Chore: set GOTOOLCHAIN=local in CI
=> Set GOTOOLCHAIN=local in CI

.github/workflows/ci-registry.yml
gofmt, goimports, go vet, Tests, and Linting are all done in the Go job.
GitHub actions should still pass.
- Chore: remove duplicated tests from ci-registry action.
=> Skip non-binary steps in ci-registry job

docs/install.md
Binaries downloaded to MacOS may be quarantined.
This documents the process to remove the quarantine attribute.
Review the installation steps.
- Doc: Update install guidance for quarantined binaries on MacOS.
=> Document method to remove quarantine on MacOS

.github/release.sh
This updates the release script to track contributors.
```shell
./.github/release.sh -d
```
- Chore: Release notes now include contributors.
=> Include contributor list in releases

blob.go, config/credhelper.go, config/docker.go, config/host.go
This clarifies some of the blob documentation around how a Put can be retried and that Get needs to be closed. It also updates the config.Host docs since concurrency and throttling is configured in there.
Documentation only changes.
- Chore: Update Go docs on blob APIs and the config.
=> Update Go docs for blob APIs and the config

cmd/regctl/artifact.go, cmd/regctl/image.go, cmd/regctl/index.go, image.go, mod/dag.go, scheme/ocidir/close.go, scheme/ocidir/close_test.go, scheme/ocidir/manifest_test.go, scheme/ocidir/referrer.go, scheme/ocidir/referrer_test.go, scheme/reg/manifest.go, scheme/reg/referrer.go, types/ref/ref.go, types/ref/ref_test.go, types/referrer/referrer.go
- Add NewHost to parse hostname or ocidir path.
- Add IsSet method to verify reference is fully defined.
- Add SetDigest and SetTag methods to create a new Ref.
- Update other packages to use new methods.
This should help with planned changes in #583.
User facing commands should be unaffected.
- Refactor the Ref package.
=> Refactor the Ref package

blob.go, image.go, manifest.go, manifest_test.go, referrer.go, tag.go, types/error.go, types/ref/ref.go, types/ref/ref_test.go
This validates the content of the reference in the various regclient methods.
Calling a regclient method without a valid reference will give an appropriate error.
- Validate references in regclient methods.
=> Validate the ref in various APIs

internal/reghttp/http.go, internal/reghttp/http_test.go
Fixes #598.
This locks the check on the backoff timeout to prevent data races.
Hopefully no user visible change, but `go test ./... -race` should not fail.
- Fix data race in the reghttp fallback timeout handling
=> Fix race in reghttp backoff timer

config/host.go, scheme/ocidir/blob.go
=> fix(race): fixed throttle locks in OCIDir and Host config

scheme/ocidir/blob.go, scheme/ocidir/blob_test.go, scheme/ocidir/ocidir.go
This extends #600 with a test.  The lock on the throttle was also moved to avoid future foot-guns.
```shell
go test ./... -race
```
- Chore: add test for ocidir throttle race.
=> Add tests for ocidir throttle race

.version-bump.lock, .version-bump.yml, Makefile
This adds a small utility to the Makefile for checking if any dependencies have had major version changes (that wouldn't be detected with a `go get -u -t ./...`).
```shell
make util-golang-major
```
- Chore: add gomajor utility to Makefile.
=> Add gomajor to check for major version updates

Makefile
Add commands to Makefile for managing releases.
```shell
make util-release-preview
```
- Chore: add commands to Makefile for managing releases.
=> Add commands in Makefile for managing releases

.github/workflows/ci-registry.yml, .github/workflows/docker.yml, .github/workflows/go.yml, .github/workflows/inactive-cleanup.yml, .github/workflows/version-check.yml, .github/workflows/vulnscans.yml
Preparing for enabling scorecard.
This specifies the token permissions on each of the GHA workflows.
GHA shouldn't fail.
- Chore: adjust token permissions on GitHub actions.
=> Set GitHub actions token permissions

README.md
Preparing for OpenSSF Scorecard.
This adds the OpenSSF Best Practices badge and includes a few other CI badges.
Badges are visible in the readme.
- Add OpenSSF Best Practices Badge.
=> Adding OpenSSF Best Practices badge

CONTRIBUTING.md, SECURITY.md
Preparing for Scorecard.
This amends the security policy with the disclosure timeline.
Documentation change to security.md.
- Chore: Include disclosure timeline in security policy.
=> Update security policy with disclosure timeline

.github/workflows/scorecard.yml, .version-bump.lock, README.md
This adds the OpenSSF Scorecard GHA workflow and badge. Some checks will report false negatives including:
- Dependency Update Tool: this project is using a side project of mine, version-check, to maintain pins on the various dependencies. This is used to allow running the updates without a 3rd party provider submitting PRs and it allows versions to be maintained in non-traditional locations (e.g. variables in the Makefile and Dockerfile).
- Pinned Dependencies: there's an open issue on scorecard for not detecting a pinned dependency from a variable and in other stages from that pinned dependency.
- SAST: gosec is run from the Makefile as a linter on commits in addition to govulncheck and osv-scanner running weekly. None of these are included in their known SAST scanners.
- Signed …
=> Add scorecard GHA and badge

CONTRIBUTING.md
The OpenSSF Best Practices recommends contributor guidelines for coding style and practices expected by the project.
This amends the contributing.md with expectations of any contributions.
Changes are to the markdown docs.
- Chore: Improve contributor guidelines.
=> Improve the contributor guidance

blob.go, scheme/reg/blob.go, scheme/reg/blob_test.go
Test for pushing blob without a descriptor, and zero length blob. This also improves documentation for the arguments to BlobPut.
No change to code behavior.
- Chore: Improve BlobPut tests.
=> Add blob tests

CONTRIBUTING.md
Cleanup some of the wording in the contributing guidelines.
Doc only changes.
=> Cleanup contributing guidelines

blob.go, image.go
Logs on a failed copy are full of context canceled warnings.
Overall the logs could use a significant trim and rework, but that will wait until a later migration to slog. This avoids logging warnings of the context canceled when a copy fails on one part and the rest of the blobs and manifest copies are canceled.
Copy to a location without permission, e.g. `regctl image copy alpine alpine-copy`
- Chore: reduce logging of context canceled messages in an image copy failure.
=> Reducing logs on canceled image copy

image_test.go, internal/copy/copy.go, tag_test.go
Adding some tests for the TagList and TagDelete APIs leveraging olareg.
```
make test
```
- Chore: Add tests for TagList and TagDelete.
=> Add tests for regclient.TagList and Delete

cmd/regctl/registry_test.go, go.mod, go.sum, image_test.go, tag_test.go
Changes to the olareg test harness now require the server to the closed to release scheduled goroutines and memory.
```shell
make test
```
- Chore: Upgrade olareg testing harness to latest version.
=> Upgrade olareg and close resources when done

Makefile
Update OSV Scanner CLI to match new synatx.
```shell
make osv-scanner
```
- Chore: Update OSV scanner to use new syntax.
=> OSV Scanner CLI syntax

.github/workflows/vulnscans.yml, Makefile
Include a check for licenses in the OSV scan. Unknown licenses are allowed because deps.dev sometimes misses them.
```shell
make osv-scanner
```
- Chore: Update OSV scanner to monitor for unapproved licenses.
=> Check licenses with OSV

example_test.go
No example usage is available in the Go docs.
Create a basic example with registry logins, to pull a manifest.
View the go doc with `godoc` (opening a browser to localhost:6060).
- Doc: Include an API example in the Go docs.
=> Adding a regclient example

cmd/regctl/artifact.go
Pushing an artifact with a `--config-type` sets `artifactType` to that value.
This allows artifacts to be pushed with `regctl artifact put --config-type ...` to only set `config.mediaType`. It also defaults a single file/layer to the `artifact-type` value if provided instead of `application/octet-stream`.
```shell
echo '{hello: "config"}' >config.json
echo hello world | regctl artifact put --config-type application/vnd.example.hello --config-file config.json localhost:5000/artifact:config-mt
echo hello world | regctl artifact put --artifact-type application/vnd.example.hello localhost:5000/artifact:artifact-type
```
- Fix: Allow pushing artifacts without an artifactType value.
=> Allow artifacts without artifact-type

docs/install.md
Add some documentation on the availability of a GitHub Actions option for installing and configuring `regctl`.
View the `docs/install.md`.
- Doc: Document the availability of the GitHub Actions installer for `regctl`.
=> Document GitHub Actions installer

cmd/regctl/registry.go
During `regctl registry login`, a `ctrl-c` does not stop the command.
Capturing a canceled context during a blocking read is difficult (involves launching a goroutine that leaks to write to a channel and then reading input from the channel with a select). So this just turns off the signal handler in `regctl registry login` so the default handler kills the process. This also cleaned up IO handling (using `cobra.Command` injected values).
```shell
regctl registry login
```
- Fix: Allow ctrl-c on `regctl registry login`
(Tests not updated since this depends on a file descriptor, terminal, and killing the process.)
=> Allow ctrl-c on regctl registry login

cmd/regctl/manifest.go, cmd/regctl/registry.go, cmd/regctl/repo.go
Somehow the manifest, registry, and repo commands were missed in the last change. This adds examples to the remaining commands.
See the help messages on various commands:
```shell
regctl manifest get --help
```
- Doc: Add examples to regctl help messages.
=> Adding more examples to regctl commands

.github/workflows/docker.yml, Makefile, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit, build/oci-image.sh
This reworks annotations on images to be based on the image labels, and to pull up common annotations to the index.
```shell
regctl manifest get ghcr.io/regclient/regctl:alpine
```
- Chore: Redesign how annotations are added to the regclient images.
=> Update image labels and annotations

README.md
Badge links for GHA workflows in the readme just open the badge picture.
This adds links to the workflows.
Click on badges in the readme.
- Chore: Add links to the GHA workflow badges.
=> Add links to GHA workflow badges

README.md
Adding another badge to the page because it's good to not just have the minimum amount of flair.
See the shiny badge on the readme.
- Doc: Include a download count badge.
=> Add a download count badge

.github/workflows/docker.yml, Makefile, build/oci-image.sh
Deprecation warnings are seen when generating SBOMs.
`syft packages` was replaced by `syft scan` in github.com/anchore/syft/pull/2446
```shell
make artifacts
```
- Fix: Replace `syft packages` with `syft scan`.
=> Update syft SBOM command

.github/workflows/coverage.yml
This adds a code coverage report as part of PRs. It should show up when changes are made to code since the last report.
GHA will generate comments in PRs when there are code changes.
- Chore: Add GitHub Action to monitor code coverage.
=> Add code coverage report in GHA

.github/workflows/coverage.yml
Limit token permission on the coverage action to the default read access.
- Chore: Limit token permission on the coverage action
=> Limit token permission on the coverage action

cmd/regctl/image.go, image.go, image_test.go
Fixes #704.
This adds a `regclient.ImageConfig` method to pull the config for a requested image.
Call `regclient.ImageConfig` or test with:
```shell
make test
```
- Feature: Add the `regclient.ImageConfig` method.
=> Add regclient.ImageConfig method

.github/workflows/vulnscans.yml
Reenabled the OSV Scanner check now that the current release supports the config override.
Run the GitHub Action.
- Chore: Reenable OSV Scanner weekly check in GitHub Actions.
=> Reenable weekly OSV Scanner GitHub Action

mod/dag.go, mod/mod.go, mod/mod_test.go
The "whitelist" term is not inclusive and needs to be replaced.
This changes the term to "known list" since it references a list of media types that are known to the tool.
No user visible change.
- Fix: Replace "whitelist" with "known list" for inclusivity.
=> Replace the whitelist term for known media types

cmd/regctl/image.go, internal/ascii/ascii.go
There's a typo in the variable name, `asciOut` should be `asciiOut`.
Fix the typo.
=> chore: Fix typo asci to ascii

pkg/archive/compress_test.go
This adds the first fuzzing test on the compression round trip.
```shell
go test -fuzz=FuzzRoundTrip ./pkg/archive
```
- Chore: Add fuzzing tests for compression.
=> Chore: Add fuzzing tests for compression

cmd/regctl/artifact.go, cmd/regctl/image.go, cmd/regctl/image_test.go, cmd/regctl/manifest.go, cmd/regctl/manifest_test.go, image.go, manifest.go, manifest_test.go, mod/config.go, scheme/ocidir/referrer.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go, types/manifest/manifest.go
The refactors the pulling of manifests by platform into the regclient library instead of duplicated with different implementations in various locations.
No user visible changes should be encountered.
- Chore: Refactor pulling manifests by platform.
=> Refactor pulling a platform specific manifest

build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
Docker's linter for Dockerfiles outputs a few warnings.
Match the case between `FROM` and `as` in the Dockerfiles and include a missing variable.
```shell
make docker
```
- Chore: Cleanup Dockerfile linter warnings.
=> Cleanup Dockerfile linter warnings

types/platform/platform.go, types/platform/platform_test.go
Allow well known architectures as a platform.
This is a shortcut permitted in containerd and other projects.
From a linux host:
```shell
regctl image config --platform arm64 regclient/regctl
```
- Allow well known architectures as a platform
=> Allow well known architectures as a platform

README.md
This adds a contributor list to the bottom of the readme.
View the readme.
- Doc: Include a contributor list in the readme.
=> Include a contributor list in the readme

mod/manifest.go
Added or deleted manifests should not be changed to replaced, only unchanged.
- Fix: Mod tracking of changed manifests
=> Fix: Mod tracking of changed manifests

cmd/regsync/main.go, cmd/regsync/regsync_test.go, cmd/regsync/root.go
Refactoring to remove globals in regsync. This also removes another usage of the internal throttle package in preparation for its removal.
- Chore: Refactoring to remove globals in regsync.
=> Chore: Refactoring to remove globals in regsync

.github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/issue.md, .github/ISSUE_TEMPLATE/question.md
Do not automatically assign myself to GitHub issues. This makes it clear that others could potentially self assign tasks they want to work on.
- Chore: Do not automatically assign myself to GitHub issues.
=> Chore: Do not automatically assign myself to GitHub issues

build/oci-image.sh
Syft isn't needed for the reproducible digest, but nice to have. This only outputs a warning rather than forcing an install.
- Fix: Add a warning if syft is not installed.
=> Fix: Add a warning if syft is not installed

mod/mod.go
An image modification to a registry that is outputting warning headers results in lots of output.
This dedupes the warning headers during an image mod. Comments were also cleaned up.
```shell
regctl image mod --to-oci alpine --create localhost:5000/library/alpine:oci
```
- Fix: Dedup warnings on image mod.
=> Fix: Dedup warnings on image mod

cmd/regbot/main.go, cmd/regbot/regbot_test.go, cmd/regbot/root.go, cmd/regbot/sandbox/blob.go, cmd/regbot/sandbox/image.go, cmd/regbot/sandbox/manifest.go, cmd/regbot/sandbox/repo.go, cmd/regbot/sandbox/sandbox.go, cmd/regbot/sandbox/tag.go, internal/reghttp/http.go, internal/sloghandle/logrus.go, internal/sloghandle/logrus_test.go, types/slog.go
Partial fix to #749.
This converts regbot to slog. It also consolidated the trace logging level to a single definition.
- Feat: Switch regbot to slog.
=> Feat: Switch regbot to slog

cmd/regctl/artifact.go, cmd/regctl/artifact_test.go, cmd/regctl/blob.go, cmd/regctl/image.go, cmd/regctl/main.go, cmd/regctl/main_test.go, cmd/regctl/manifest.go, cmd/regctl/registry.go, cmd/regctl/repo.go, cmd/regctl/root.go, cmd/regctl/tag.go
Partial fix for #749.
This switches regctl to use slog for logging. This also removed the global `log` variable.
```shell
regctl -v trace tag ls alpine
```
- Feat: Switch regctl to slog.
=> Feat: Switch regctl to slog

cmd/regsync/main.go, cmd/regsync/regsync_test.go, cmd/regsync/root.go
Partial fix for #749.
This converts `regsync` to `slog`, finishing the last of the commands.
- Feat: Switch regsync to slog.
=> Feat: Switch regsync to slog

.github/workflows/go.yml
The previous body string was broken in an update, no longer interpreting the encoded linefeeds.
Inject release notes by file using the `body_file` option.
This will be verified in the next release.
- Fix: Inject release notes by file.
=> Fix: Inject release notes by file

cmd/regctl/image.go, mod/config.go, mod/mod_test.go
Fixes #864.
This allows environment variables to be added or removed from images.
```shell
regctl image mod nginx --env "[linux/amd64]NGINX_VERSION=1.27.3-custom" --create localhost:5002/library/nginx:custom
regctl image inspect --platform linux/amd64 localhost:5002/library/nginx:custom
docker run -it --rm localhost:5002/library/nginx:custom env
```
- Feat: Image mod environment variables.
=> Feat: Image mod environment variables

cmd/regctl/image.go
Remove unused short arg parameters to simplify the various cobra flags, only specifying a short arg when it is used.
- Chore: Remove unused short arg parameters.
=> Chore: Remove unused short arg parameters

docs/install.md
Partial update for #872.
Document some of the community maintained packages of regclient.
This is a documentation only update.
- Feat: Document community maintained packages.
=> Feat: Document community maintained packages

cmd/regsync/config.go, cmd/regsync/regsync_test.go, cmd/regsync/root.go, docs/regsync.md
This adds support for copying images with external referrers, both as a source and/or target, in regsync.
New fields are documented in regsync.md.
- Feat: Support external referrers in regsync.
=> Feat: Support external referrers in regsync

image.go
Unit tests periodically fails when copying external referrers.
The `imageSeenOrWait` would falsely hit on a digest pushed to a separate repository, skipping the copy of a blob when it should not.
```shell
go test .
```
- Fix: Handle repeated digest in copy with external referrers.
=> Fix: Handle repeated digest in copy with external referrers

cmd/regbot/root.go, cmd/regctl/root.go, cmd/regsync/root.go
log/slog does not have fatal or panic log levels, so this removes them from the CLI help messages and tab-complete.
```shell
regctl --help
```
- Fix: Align log levels with slog.
=> Fix: Align log levels with slog

internal/auth/auth.go, internal/auth/auth_test.go
Fixes #907.
Allow authentication with a token. This fixes a regression caused by PR #893. Now logins using a token do not skip the POST request logic.
- Fix: Allow authentication with a token.
=> Fix: Allow authentication with a token

cmd/regbot/regbot_test.go, cmd/regbot/root.go, cmd/regctl/artifact.go, cmd/regctl/blob.go, cmd/regctl/completion.go, cmd/regctl/config.go, cmd/regctl/digest.go, cmd/regctl/image.go, cmd/regctl/index.go, cmd/regctl/main.go, cmd/regctl/manifest.go, cmd/regctl/ref.go, cmd/regctl/registry.go, cmd/regctl/repo.go, cmd/regctl/root.go, cmd/regctl/tag.go, cmd/regsync/regsync_test.go, cmd/regsync/root.go
This helps align the different commands with each other.
- Variable names have been improved to be less confusing.
- Flags have been sorted, and completion options added on some flags where missing.
- Each command creates its own options to avoid default flag value conflicts.
- Reusing a command under two paths is now done by calling that commands "new" function.
- Global-but-not-really-global options have been moved to be associated with the specific commands that use them.
Most changes should not be user visible. And where changes are visible, like moving flags from global to a specific command, they should be an improvement. Examples on some of the aliased commands may be changed to show the primary command name.
- Chore: Refactor cobra commands.
=> Chore: Refactor cobra commands

docs/hub-regbot.md, docs/hub-regctl.md, docs/hub-regsync.md
Docker Hub repositories must include required links to conform to the Docker Sponsored Open Source program.
Include Docker Hub repository documentation.
These markdown files are manually copied to the Docker Hub repository.
- Doc: Include Docker Hub repository documentation.
=> Doc: Include Docker Hub repository documentation

docs/hub-regsync.md
Fixes #919.
Update regexp in Hub readme (this was also directly updated on Hub).
Other regexp examples are migrating to <https://regclient.org> and will eventually be removed from this repo.
- Fix: Escape regexp example.
=> Fix: Escape regexp example

internal/auth/auth.go, internal/auth/auth_test.go
This adds support for a relative path in the bearer token URL. This is unlikely to be encountered on large registries, but feasible for a minimal registry implementation to combine both the token server and registry server on the same instance, or at least behind the same reverse proxy.
```shell
make test
```
- Feat: Allow relative urls in bearer auth.
=> Feat: Allow relative urls in bearer auth

Makefile
Add a "make clean" command that removes directories created by various make commands.
```shell
make clean
```
- Chore: Add a "make clean" command.
=> Chore: Add a "make clean" command

cmd/regctl/repo.go, cmd/regctl/repo_test.go
Add a `regctl repo copy` command. This is a first pass without any output or progress.
```shell
regctl repo copy --include 'v0\.4.*' regclient/regctl localhost:5000/regclient/regctl
```
- Feat: Add regctl repo copy.
=> Feat: Add regctl repo copy

cmd/regctl/image.go
Remove the field since it isn't used. This was previously planned to estimate the remaining time in the transfer.
- Chore: Remove the unused bps field.
=> Chore: Remove the unused bps field
