Makefile, cmd/regctl/error.go, cmd/regctl/main.go, cmd/regctl/registry.go, go.mod, go.sum, regclient/config.go
This adds a prompt for the password without echoing out to the screen (tested in Linux). Also included:
- Makefile now includes a `go mod vendor` since I ran into issues adding another dependency.
- Environment variable in regclient is no longer regctl specific and can be configured.
- Username can be blank/unset and the previous username will be reused.
=> Add prompt for user/pass on registry login

Makefile, README.md, docker-plugin/docker-regclient
This adds a small wrapper script so regctl can be called as a docker CLI plugin.
=> Adding docker CLI plugin wrapper

cmd/regctl/image.go, regclient/error.go, regclient/manifest.go, regclient/regclient.go, regclient/tag.go
Adding support for HEAD requests when pulling the manifest digest avoids hitting the rate limited APIs on Docker Hub.
=> Adding manifest HEAD request support

regclient/image.go
This avoids pulling the manifest, which avoids touching Hub rate limits if the target image is already up-to-date.
=> Adding manifest HEAD check before image copy

cmd/regctl/template.go, pkg/auth/auth.go, pkg/auth/error.go, pkg/retryable/retryable.go, regclient/image.go, regclient/regclient.go
- Template adds time functions
- Auth handles a race condition where two requests both see auth request
and second request would fail thinking auth already attempted.
- Retryable passes context to http request to allow cancel.
- Retryable checkResp is cleaned up for better logging.
- Image copy shows source and target in debug logs.
- regclient checks for docker.io in hostname.
- regclient locks before modifying hash of shared objects
=> Various concurrency fixes

cmd/regctl/template.go, cmd/regsync/config.go, cmd/regsync/root.go, cmd/regsync/template.go, regclient/regclient.go
- regsync config: allow default backup value, expand templates on
user/pass and source/target fields
- regsync: cleanup logging and error handling
- templates: adding templates for default, env, and file
- regclient: Bug fix with empty scheme on host
=> More regsync templates, bugfixes, and cleanup

.github/workflows/docker.yml, .github/workflows/go.yml, Makefile, README.md, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/build-artifacts.sh, cmd/regbot/config.go, cmd/regbot/error.go, cmd/regbot/main.go, cmd/regbot/root.go, cmd/regbot/sandbox/error.go, cmd/regbot/sandbox/image.go, cmd/regbot/sandbox/reference.go, cmd/regbot/sandbox/repo.go, cmd/regbot/sandbox/sandbox.go, cmd/regbot/sandbox/tag.go, docs/README.md, docs/regbot-quickstart.md, docs/regsync-quickstart.md, go.mod, go.sum, pkg/go2lua/convert.go
This adds the `regbot` command and image that can be used to run Lua scripts with the registry API to manage registries, creating complex mirroring rules and cleanup policies.
=> Adding regbot

cmd/regctl/registry.go, docs/regbot-quickstart.md
`regctl registry` commands `login`, `logout`, and `set` previously required the nonintuitive DNS name "registry-1.docker.io" for Hub. They now accept "docker.io" and default to Hub when no registry is provided.
=> Defaulting regctl registry commands to Hub

cmd/regctl/tag.go
This modifies the output of `regctl tag ls`. To show the old tag output, you can format the output with the option:
```
--format '{{ $name := .Name }}{{ range .Tags }}{{ printf "%s:%s\n" $name . }}{{ end}}' 
```
=> Change regctl tag ls to return json and allow formatting

cmd/regbot/main.go, cmd/regbot/root.go, cmd/regctl/main.go, cmd/regsync/main.go, cmd/regsync/root.go
This creates unique user-agent headers including regclient/regctl, regclient/regsync, and regclient/regbot.
=> Updating user-agent header per command

cmd/regbot/config.go, cmd/regbot/sandbox/image.go, cmd/regctl/config.go, cmd/regctl/image.go, cmd/regsync/config.go, cmd/regsync/root.go, docs/README.md, go.mod, go.sum, regclient/blob.go, regclient/config.go, regclient/image.go, regclient/manifest.go, regclient/regclient.go, regclient/repo.go, regclient/tag.go
This update continues to refactor away some of the old design decisions like removing DNS and Scheme from the various calls. It also adds Docker Schema v1 support, which while deprecated, is still seen in some older images. This also fixes some yaml parsing issues.
=> Refactoring

cmd/regbot/sandbox/reference.go, docs/README.md, docs/examples/regsync.yml
- Wrap on sentences for better diffs in git.
- Document change in regctl layers to blobs.
- Document mirrors and priority.
- Document media type usage.
- Document version command.
- Document printPretty template.
- Document regbot ref:digest
This also fixes a new reference issue in regbot and adds a digest method to references.
=> Updating docs

cmd/regctl/image.go, regclient/manifest.go
After pulling a manifest list, only do one GET to resolve the platform,
without a second GET for the desired platform manifest.
=> Update regctl for digest pull

cmd/regsync/config.go, docs/README.md
This allows the registry field to have templates, which may be useful in CI pipelines that pass the local registry name as a variable.
=> regsync: allow registry field to be templated

Makefile, README.md, cmd/regbot/sandbox/image.go, cmd/regbot/sandbox/reference.go, cmd/regctl/blob.go, cmd/regctl/image.go, cmd/regctl/manifest.go, cmd/regctl/tag.go, cmd/regsync/root.go, regclient/blob.go, regclient/image.go, regclient/manifest.go, regclient/manifest/common.go, regclient/manifest/docker1.go, regclient/manifest/docker2.go, regclient/manifest/error.go, regclient/manifest/manifest.go, regclient/manifest/oci1.go, regclient/manifest/unknown.go, regclient/regclient.go, regclient/tag.go, regclient/types/ratelimit.go, regclient/types/ref.go
This also refactored manifests to not create them inside of the ManifestGet call, and instead pulled them out into a separate package that creates the appropriate manifest based on the content type or original manifest struct.
=> Support regctl manifest and blob put

cmd/regctl/registry.go
This improves the error message seen in #46 
=> Improve error message when TTY unavailable on password prompt

cmd/regbot/sandbox/blob.go, cmd/regbot/sandbox/image.go, regclient/blob.go, regclient/blob/blob.go, regclient/blob/common.go, regclient/blob/ociconfig.go, regclient/blob/reader.go
Like the manifest refactor, this moves blobs out to a separate package. Additionally the blob reader now checks the digest and size as the blob is read.
=> Blob refactor

cmd/regctl/registry.go, pkg/auth/auth.go, pkg/retryable/retryable.go, regclient/blob.go, regclient/http.go, regclient/image.go, regclient/manifest.go, regclient/regclient.go, regclient/tag.go
This supports the docker credential helpers for ECR and GCR when run as a binary (from within a container, you would need to include the helper binary and it's source of credentials). Support for using IdentityToken values still needs testing, but that has not been seen from these registries (they each use a generic user value instead). For GCR support, the auth needed to be redesigned to update the scope in the auth request because the www-authenticate header is not valid for push requests.
Fixes #54
=> Adding ECR and GCR support

cmd/regctl/completion.go, cmd/regctl/image.go, pkg/archive/compress.go, pkg/archive/errors.go, pkg/retryable/error.go, pkg/retryable/retryable.go, regclient/blob.go, regclient/error.go, regclient/http.go, regclient/image.go, regclient/manifest.go, regclient/manifest/docker1.go, regclient/manifest/docker2.go, regclient/manifest/manifest.go, regclient/manifest/oci1.go, regclient/manifest/unknown.go, regclient/regclient.go, regclient/repo.go, regclient/tag.go
This adds the ability to export images to OCI Layout format, which supports multi-platform images. It also adds the ability to import from the OCI Layout (or the already supported `docker save` tar syntax). This facilitates air-gapped workflows.
=> Adding OCI Import/Export

cmd/regbot/config.go, cmd/regbot/root.go, cmd/regsync/config.go, cmd/regsync/root.go
When running a "once" action on regbot and regsync without defining parallel or defining it to a value of 0 or less, run steps in order without any concurrency.
This also adjusts some error handling on regsync when one bad image is encountered, continuing to the process the remaining images.
=> Adjust parallel=0 with "once" commands

pkg/auth/auth.go, pkg/retryable/retryable.go, regclient/blob.go, regclient/error.go, regclient/http.go, regclient/manifest.go, regclient/tag.go
This updates various APIs to restrict the expected HTTP status code, adds the tag delete API, and falls back to other methods when possible.
=> Supporting OCI distribution-spec

cmd/regctl/manifest.go, regclient/manifest/manifest.go
Buildkit cache manifests don't have a platform, which was breaking `regctl manifest get`.
=> Fix error handling with regclt on buildkit cache

regclient/image.go, regclient/regclient.go
This updates the image copy to properly handle buildkit caches that appear as an OCI index that points to blobs instead of manifests.
=> Support buildkit cache

cmd/regbot/config.go, cmd/regbot/root.go, cmd/regctl/config.go, cmd/regctl/registry.go, cmd/regctl/root.go, cmd/regsync/config.go, cmd/regsync/root.go, docs/regbot.md, docs/regsync.md, regclient/blob.go, regclient/blob_test.go, regclient/config.go, regclient/regclient.go
This adds the ability to configure chunk sizes per registry, and the ability to disable the automatic chunking of large blobs. Set the blob max to `-1` to disable. By default, pushing a blob over 100MB will switch to sending as 1MB chunks.
In regctl, `regctl registry set` has options for `--blob-chunk` and `--blob-max`.
In regsync and regbot, the creds section for each registry supports the `blobMax` and `blobChunk` options.
=> Add blob size limits to commands

build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
Cache for the helper builds were being broken by changes to the regclient source. This splits the setup of a golang builder target from the regclient dev target.
=> Cache credential helpers in build

regclient/image.go
The OCI layout always wraps the target image in an index, and that descriptor in the top level index contains an annotation for the tag. This supports importing from buildkit/buildx produced images.
=> Fixing OCI export/import

cmd/regbot/sandbox/image.go, cmd/regctl/image.go, regclient/image.go
- Makes rc.ImageImport easier to test
- regctl export now allows a filename
=> Use ReadSeeker for import

cmd/regctl/artifact.go, cmd/regctl/blob.go, cmd/regctl/manifest.go
This adds a `regctl artifact` command to push/pull OCI artifacts.
=> Adding artifact support to regctl

cmd/regctl/artifact.go, cmd/regctl/blob.go, cmd/regctl/manifest.go, docs/regctl.md
The `regctl artifact get --strip-dirs` flag is useful for pulling ORAS tar artifacts that include the directory name in both the filename and inside the tar. This removes on layer of repetitiveness. Cobra commands were updated to remove redundant `put` aliases. And docs are also updated to add `regctl blob pub` and `regctl artifact`.
=> Updating docs and adding artifact strip-dirs flag

cmd/regsync/root.go
n/a
Bug fix: if a registry gets a corrupt image, due to a nested blob or manifest being deleted, the backup would fail and stop the image sync. This ignores those errors allowing the sync to recover from a broken image.
On an image being synced, delete a nested manifest or blob and verify the sync only outputs a warning rather than a blocking error.
Regsync no longer blocks on a failing backup
=> Only warn on regsync backup errors

cmd/regbot/sandbox/image.go, cmd/regctl/config_unix.go, cmd/regctl/config_windows.go, cmd/regctl/image.go, cmd/regsync/config.go, cmd/regsync/root.go, docs/regbot.md, docs/regsync.md, regclient/image.go
n/a
This adds additional options to the image copy:
- Digest tags: Triggers an additional copy of the tag `sha256-<digest>.*` with every manifest copy. These tags are used with tools like cosign.
-  Force recursive: Runs the copy command recursively through manifests and blobs even if the parent manifest already exists at the target. This can be used to repair a broken registry (deleting child manifest or blobs without deleting the parent) or updating digest tags.
- Platforms: Sparsely copies a multi-platform image with only specific platforms copied. This is currently experimental and untested since it requires registry support to disable validation of manifests.
```
regctl image copy --digest-tags --force-recursive …
```
=> Adding options to image copy

regclient/manifest/manifest.go, regclient/manifest/manifest_test.go
n/a
One of the manifest refactors to eliminate duplication of digest calculations broke for the schema v1 manifests that compute their digest differently. This fixes that regression and adds some tests.
Perform a `regctl image copy debian:6 localhost:5000/library/debian:6`.
n/a
=> Fix handling of schema v1 manifests

cmd/regbot/config.go, cmd/regctl/config.go, cmd/regctl/registry.go, cmd/regctl/root.go, cmd/regsync/config.go, cmd/regsync/root.go, regclient/config.go, regclient/config_test.go, regclient/error.go, regclient/http.go, regclient/manifest_test.go, regclient/tag.go
Fixes #125 
This adds a new host setting, 'APIOpts' with a key value map for injecting specific options into various parts of the API. Currently the only option is "disableHead" which can be set to "true" to disable HEAD requests on registries that don't support them.
For regctl:
```
regctl registry set --api-opts disableHead=true ...
```
And for regsync:
```yaml
creds:
- registry: localhost:5000
tls: disabled
apiOpts:
disableHead: "true"
```
With that setting, images can be copied to or from a registry that doesn't have support for HEAD requests.
Handle registries without HEAD support
Holding off on documentation to ensure I want to support this feature long-term.
=> Handle registries without HEAD support

regclient/tag.go
n/a
Bug fix for deleting OCI manifests on registries without the tag delete API. This corrects the schema version and adds a media type to the temporary manifest that is pushed.
On a registry where deletes for manifests are enabled by the tag delete API isn't available yet, run a `regctl tag rm` on an OCI manifest (I've been testing with cosign signatures since they are an OCI image media type). Before the fix, a registry would reject the bad temporary manifest with a 500 code.
Fix for deleting tags pointing to an OCI manifest
=> Fix delete of tags to OCI manifests

.github/workflows/docker.yml, Makefile
Fixes #139 
The version injection wasn't being triggered with the CI builds. This moves the prereq in the Makefile and cleans up the GHA.
CI builds should have version information in both the built binaries and docker images once merged.
=> Fixing version injection in CI

Makefile
Fixes #139 for docker.
Docker builds were reporting the version as dirty because `.dockerignore` made it appear that multiple files were deleted. This moves the version check to the Makefile before calling `docker build` instead of from within the build container.
Docker images will show a commit without the `-dirty` tag when git repo is clean.
=> Fixing dirty version in docker builds

.github/workflows/docker.yml
Fixes #139 
Docker builds from the Makefile are good, but GHA skips the Makefile, so this includes the embed/version.json set in the GHA.
Docker images from GHA will have a version.
=> Generate embed/version.json in docker GHA

internal/reghttp/http.go, scheme/reg/blob_test.go, scheme/reg/repo.go, scheme/reg/tag.go, types/blob/blob_test.go
This should help with #143 
Doing a tag rm with authentication when the blob server is remote resulted in a failure because the temporary blob didn't support seeking on the reader. This fixes the reader and adds tests to the blob calls to verify the auth is supported using the same credentials.
Remote a tag on a registry that doesn't support the new API calls, where the blob upload location is on a different hostname.
Fix for tag rm with authentication when the blob upload location is a different host
=> Handle tag rm with auth on a remote blob host

cmd/regbot/sandbox/image.go, cmd/regbot/sandbox/manifest.go, cmd/regctl/artifact.go, cmd/regctl/image.go, cmd/regctl/manifest.go, cmd/regsync/root.go, image.go, manifest_test.go, scheme/ocidir/blob_test.go, scheme/ocidir/close.go, scheme/ocidir/manifest.go, scheme/ocidir/manifest_test.go, scheme/reg/manifest.go, scheme/reg/manifest_test.go, scheme/reg/tag.go, types/manifest/common.go, types/manifest/docker1.go, types/manifest/docker2.go, types/manifest/manifest.go, types/manifest/manifest_test.go, types/manifest/oci1.go
This is a lot of refactoring to cleanup the interface and handle a new SetOrig interface.
Tests have been added, and further commits for blob and modification methods are coming.
Refactored the manifest type. This results in breaking changes to exported methods.
Added the ability to modify a manifest type.
=> Refactoring manifest interface, adding SetOrig

blob.go, blob_test.go, scheme/ocidir/blob_test.go, scheme/reg/blob_test.go, types/blob/blob.go, types/blob/blob_test.go, types/blob/common.go, types/blob/ociconfig.go, types/blob/reader.go
This refactors the blob type to have a similar interface to the manifest type. It also adds a SetConfig method to allow modifying an OCI config blob.
Tests have been added.
Blob methods have been refactored with breaking changes to exported APIs.
Blob SetConfig method added to allow modifying an OCI config.
=> Refactor blob like manifests, add SetConfig

cmd/regbot/config.go, cmd/regctl/config.go, cmd/regctl/registry.go, cmd/regctl/root.go, cmd/regsync/config.go, config/host.go, docs/README.md, docs/regbot.md, docs/regsync.md, internal/auth/auth.go, internal/auth/auth_test.go, internal/reghttp/http.go, internal/reghttp/http_test.go, regclient.go
Fixes #149 
This adds a new `repoAuth` option (`repo-auth` in regctl) to setup a separate auth per repository instead of for the entire registry.
Use regsync to concurrently copy multiple repositories. Without the `repoAuth` option, it will fail:
```yaml
version: 1
creds:
- registry: gcr.io
repoAuth: true
- registry: docker.io
defaults:
ratelimit:
min: 50
retry: 15m
parallel: 2
interval: 30m
backup: "bkup-{{.Ref.Tag}}"
sync:
- source: "regclient/regctl:edge"
target: "gcr.io/project-name/regctl:edge"
type: image
- source: "regclient/regsync:edge"
target: "gcr.io/project-name/regsync:edge"
type: image
```
Added repoAuth option for gcr.io support.
=> Adding repoAuth for gcr.io

image.go
Fixes #164 
The manifest descriptor may not have annotations already. This fixes a nil map error.
`regctl image export <image> <tar-filename>`
=> Fix nil map error on image export

cmd/regctl/image.go, cmd/regctl/manifest.go
Requiring `--list` on manifest digest and get commands could be confusing and hide multi-platform images. This defaults to list being enabled, and users can provide `--platform local` to resolve their local environment (or use `--list=false`).
The following now default to returning the manifest and digest of the list for multi-platform images:
```shell
regctl image digest
regctl image get
regctl manifest digest
regctl manifest get
```
Default to displaying manifest lists in regctl
=> regctl defaults to manifest list

types/ref/ref.go, types/ref/ref_test.go
After reworking the Ref parsing for registry types, the original reference was not stored. Fix fixes the issue.
Do not replace the ref struct being returned, instead edit the struct.
`regctl manifest get` on a manifest list will show the original name.
=> Ref should to store original value

internal/units/size.go, types/descriptor.go, types/manifest/docker2.go, types/manifest/manifest_test.go, types/manifest/oci1.go
This adds a pretty printer for image manifests.
```shell
$ regctl manifest get --platform local regclient/regctl:latest
Name:        regclient/regctl:latest
MediaType:   application/vnd.docker.distribution.manifest.v2+json
Digest:      sha256:41770c110431b0ffc5f577aa44968bfbfd79e92eb0929e37f006179fd4aeddcc
Total Size:  3.67MB
Config:      
Digest:    sha256:3615d1937a8fe8708e041e94f4abb544196380e12628bacdcde0a7eaf1a693ba
MediaType: application/vnd.docker.container.image.v1+json
Size:      3024B
Layers:      
Digest:    sha256:f6e2d7fa40092cf3d9817bf6ff54183d68d108a47fdf5a5e476c612626c80e14
MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
Size:      941B
Digest:    sha256:92365f35877078c3e558e9a66ac083fe9a8d44bdb3150bdac058380054b …
```
=> Adding a pretty printer for image manifests

cmd/regbot/config.go, cmd/regbot/root.go, cmd/regctl/root.go, cmd/regsync/config.go, cmd/regsync/root.go, docs/regbot.md, docs/regsync.md
Fixes #145
This adds options to override the user-agent header in `regctl`, `regsync`, and `regbot`.
For `regctl`: `regctl --user-agent override/value ...`
For `regsync` and `regbot`:
```
defaults:
userAgent: "override/value"
...
```
Allow the user-agent to be overridden.
=> Allow overriding the user-agent

blob.go, blob_test.go, cmd/regctl/manifest.go, image.go, manifest.go, manifest_test.go, types/descriptor.go, types/descriptor_test.go
When the data field is defined in the descriptor, attempt to parse and use it instead of fetching from the registry.
Define an image with the Data field in the manifest, when fetching the image to copy, a query should not be made for those manifests or blobs.
Support the Data field in the descriptor on manifest and blob gets
=> Parse the descriptor data field when available

scheme/ocidir/blob_test.go, scheme/ocidir/manifest.go, scheme/ocidir/manifest_test.go, scheme/ocidir/ocidir.go
This fixes cases when both a tag and digest match two separate descriptors on a manifest push to an ocidir, where the tag is being replaced by a descriptor that was first pushed by digest. The first entry is replaced and now later entries are deleted.
This will show up with the future `regctl image mod` command.
Fix an issue with dangling references in the ocidir index.json.
=> Fix ocidir index.json dangling entries

internal/rwfs/os.go, internal/rwfs/os_test.go
Relative paths with the rwfs library would fail on a `..`. This corrects the handling when the root is not fixed.
Use `ocidir://../path:latest` in a regctl command.
Fix handling of relative paths in `ocidir`.
=> Fix handling of relative OS paths

regclient.go
Fixes #178 
The handling for `/etc/docker/certs.d` incorrectly treated this as file instead of a directory of host certs.
Access a registry with a private certificate and copy the certificate or ca to `/etc/docker/certs.d/ca.crt`.
Fix handling of `/etc/docker/certs.d`
My local e2e tests have been updated, but these are not pushed to the repo yet.
=> Fix handling of docker certificates

scheme/ocidir/tag.go, scheme/ocidir/tag_test.go
This reports an error when deleting a missing tag from an ocidir.
`regctl tag rm ocidir://path:tag`
=> Handle missing tag on ocidir tag rm

.dockerignore
The docker build was broken after moving the mod interface to a new package name.
Fixing the docker build with a new directory reincluded in `.dockerignore`.
`make docker`
=> Fixing docker build with new mod directory

build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync.buildkit
Hopefully fixes GHA build failures.
I may have found an edge case with `COPY --link --chown...`. Removing `--link` from those lines for now.
GHA for Docker build should succeed.
=> Reverting "link" on dockerfile copy with chown

build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync.buildkit
GHA builds with `COPY --link --chown=appuser` were failing, likely because of an older version of docker in GHA. This moves over to fixed uid/gid which is needed for `--link` to work anyway.
GHA docker builds won't fail.
=> Switching to fixed uid/gid in docker builds

.github/workflows/go.yml, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit, go.mod, mod/config.go
Go 1.16 is no longer supported. Upstream tools like staticcheck no longer work with 1.16.
All instances of 1.16 were updated to 1.17. `go mod tidy` and `go mod vendor`.
CI should succeed.
Upgrade to Go 1.17
=> Updating Go from 1.16 to 1.17

docs/README.md, pkg/template/template.go
Fixes #192 
Go 1.18 has deprecated `strings.Title`: https://github.com/golang/go/issues/48367
This removes the template that calls this function.
Format strings that use `title` will no longer work.
Breaking: format templates no longer support `title`
=> Remove deprecated title template function

LICENSE, Makefile
This also fixes a minor license detail.
Using `-trimpath` on go build, removing host specific details from output binary.
Searching the binary should not show any host specific paths.
Go build now runs with `-trimpath`
=> Setting trimpath on go build

internal/reghttp/http.go
Running through a proxy did not work.
The default transport needed to be used instead of an empty transport when setting up a new client.
Running with `https_transport` defined uses that proxy.
Fix handling of http_proxy and https_proxy
=> Use default transport instead of empty transport

scheme/ocidir/manifest.go, scheme/ocidir/manifest_test.go, scheme/ocidir/tag_test.go, scheme/ocidir/testdata/regctl/index.json
Manifest head on an ocidir with a digest was giving a false positive.
Updates manifest head to follow the same logic as manifest get, and also parses the file for the media type and size.
Image export to an ocidir of an index should not be missing manifests.
Fix: manifest head on an ocidir with a digest won't succeed if manifest is missing
=> Fix manifest head with digest on ocidir

README.md
Fixes #201 
Most commands do not need a tty, and including it outputs carriage-returns that break a few things. This changes updates the readme with better directions.
This should output `0`:
```
regctl image digest alpine | grep -c $'\r'
```
=> Remove tty from example container commands

cmd/regsync/config.go, cmd/regsync/regsync_test.go, cmd/regsync/root.go, docs/regsync.md
This is an alternative for #204 
The source and target fields of regsync now support a `.Sync` template variable that can be used to query other settings within the sync entry.
Using a regsync.yml file similar to the following allows the target to be based on the source in a reusable way:
```yml
version: 1
creds:
- registry: registry:5000
tls: disabled
x-sync-hub: &sync-hub
target: registry:5000/hub/{{ .Sync.Source }}
type: repository
x-sync-gcr: &sync-gcr
target: registry:5000/gcr/{{ index (split .Sync.Source "gcr.io/") 1 }}
type: repository
sync:
- <<: *sync-hub
source: alpine
tags:
allow:
- 3
- 3.9
- latest
- <<: *sync-hub
source: busybox
tags:
allow:
- latest
- <<: *sync-gcr
source: gcr.io/example/repo
tags:
allow:
- 1
- 1.5
- latest …
```
=> Add template vars to regsync source and target

mod/mod_test.go, types/docker/schema2/manifest.go, types/docker/schema2/manifestlist.go, types/manifest/docker2.go, types/manifest/manifest.go, types/manifest/manifest_test.go, types/manifest/oci1.go
This adds support for annotations on docker2 manifest types. This may not be supported on registries that reject unknown fields.
```
regctl image mod --annotation key=value registry.example.org/repo/image:tag --create new-tag
```
Add support for annotations on docker2 schemas
=> Support annotations on docker2 media types

scheme/ocidir/manifest_test.go, scheme/ocidir/ocidir.go
Pushing a second tag to the same digest in ocidir would result in deleting the first tag.
Handling new entries to index.json has been fixed for entries with another tag.
```shell
regctl image copy regclient/regctl ocidir://repo:regctl1
regctl image copy regclient/regctl ocidir://repo:regctl2
regctl tag ls ocidir://repo
```
Fix handling of ocidir when multiple tags point to the same digest
=> Handle multiple tags to same digest in ocidir

.github/workflows/docker.yml
This adds image signing from cosign as described in https://blog.chainguard.dev/zero-friction-keyless-signing-with-github-actions/
After merge to main, images will be signed
Adding image signing with cosign
=> GHA image signing with cosign

cmd/regctl/image.go, mod/mod.go
`regctl image mod` called the wrong functions for `volume-rm` and `expose-rm`.
This calls the right functions on the rm commands.
`regctl image mod --expose-rm ...` or `regctl image mod --volume-rm ...`
Fix: regctl image mod args for expose and volume rm actually rm
=> Fixing args to regctl mod

cmd/regctl/image.go
Fixes handling of boolean args to `regctl image mod` without the `=true` default.
This configures the arg as a bool with a `NoOptDefVal` setting.
`regctl image mod --to-oci --create $target $source`
=> Fix handling of boolean args to image mod

blob.go, blob_test.go, cmd/regbot/sandbox/image.go, cmd/regctl/image.go, cmd/regsync/config.go, cmd/regsync/root.go, image.go, manifest_test.go, mod/manifest.go, mod/mod.go, mod/mod_test.go, regclient/manifest/manifest.go, regclient/mediatype.go, regclient/types/mediatype.go, scheme/reg/blob.go, scheme/reg/blob_test.go, scheme/reg/manifest_test.go, types/descriptor_test.go, types/mediatype.go
- Attempt to pull external blob from registry
- Handle blob pull to external URL
- Copy option to copy external blobs
- Mod option to remove external URLs from descriptors
Mod of an image with external layers no longer fails.
- Blob pull of external URL first attempts to pull directly from the registry, then loops through external URLs.
- Image copy now has an option to copy external blobs
- Image mod now has an option to remove external URLs from descriptors
- `types.MediaTypeDocker2Layer` renamed to `types.MediaTypeDocker2LayerGzip`
`regctl image mod ...` with actions on layers no longer fails for images with external layers.
Feature: Improve handling of external URLs
Breaking: Media type variable for docker image layers has been renamed
=> Improve handling of external URLs

types/manifest/manifest.go, types/manifest/manifest_test.go
The content-length header was not properly imported from manifest head requests.
This sets the correct variable for the manifest size.
Verify the descriptor from a manifest head request.
Fix: manifest head request now set the descriptor size correctly.
=> Fix size extracted from manifest head request

scheme/ocidir/ocidir.go
The `config` value conflicts with a possible regclient import, so it was renamed.
Nothing breaks.
=> Rename config to avoid import conflicts

types/manifest/docker1.go, types/manifest/docker2.go, types/manifest/manifest.go, types/manifest/oci1.go
With annotations defined on many manifest media types (even if not defined in upstream specs), a get/set method is added to improve usability.
Run a get/set on an annotation on a manifest.
=> Adding manifest get/set annotation methods

cmd/regctl/artifact.go, scheme/ocidir/referrer.go, scheme/reg/referrer.go, types/manifest/docker1.go, types/manifest/docker2.go, types/manifest/manifest.go, types/manifest/manifest_test.go, types/manifest/oci1.go, types/mediatype.go, types/oci/v1/artifact.go
This adds experimental support for a new OCI artifact manifest type. This is not considered stable until approved by the OCI.
This requires a registry with the new media type support, see [oci-playground/distribution](https://github.com/oci-playground/distribution) for an example.
```
echo hello oci | regctl artifact put --refers \
--annotation org.opencontainers.artifact.type=misc \
--annotation org.example.test=hello \
--annotation org.example.location=oci \
--manifest-media-type application/vnd.oci.artifact.manifest.v1+json \
$registry/$repo:$tag
regctl artifact list $registry/$repo:$tag
```
Experimental: adding support for OCI artifact media type
Documentation is not included for experimental features.
=> Experimental support for artifact manifest type

build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
Go has deprecated `go get` for installing binaries.
Change `go get` to `go install` for external binaries.
Docker builds will continue to work.
=> Update go get to go install

types/ref/ref.go, types/ref/ref_test.go
A `regctl tag ls localhost:5000` tries to connect to localhost with an empty repository, parsing the 5000 as a tag.
When localhost is pulled up as a registry, a missing repository value is now considered an error.
`regctl tag ls localhost:5000`
=> Detect errors with localhost ref without a repo

config/credhelper.go, config/credhelper_test.go, config/docker.go, config/docker_test.go, config/host.go, config/host_test.go, config/testdata/docker-config.json, config/testdata/docker-credential-test, internal/conffile/conffile.go, internal/conffile/conffile_test.go, internal/conffile/conffile_unix.go, internal/conffile/conffile_windows.go, internal/conffile/homedir.go, internal/timejson/timejson.go, internal/timejson/timejson_test.go
This adds support for parsing the docker config.json directly. This will remove an external dependency and also allow for calling credential helpers only when they are needed.
This isn't externally visible yet.
=> Add support for parsing docker config directly

cmd/regctl/artifact.go, scheme/ocidir/referrer.go, scheme/ocidir/referrer_test.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go, types/docker/schema2/manifest.go, types/manifest/docker2.go, types/manifest/manifest.go, types/manifest/manifest_test.go, types/manifest/oci1.go, types/oci/v1/artifact.go, types/oci/v1/manifest.go
The experimental refers field should be omitted when not used. This switches the field to a pointer so the json marshaling can detect the nil value.
`regctl image mod` on a supported manifest type (docker image, OCI image, OCI artifact) does not result in an empty `refers: {}` field.
=> Refers field needs to be a pointer for "omitempty"

cmd/regctl/artifact.go, cmd/regctl/image.go, image.go, referrer.go
Allow referrers to be queried for a recursive image copy.
`regctl image copy --referrers src:tag dst:tag`
Still no e2e tests that would be useful here, and docs not provided for experimental features.
=> Support referrers with image copy

cmd/regctl/artifact.go, image.go, types/manifest/docker2.go, types/manifest/oci1.go
- `regctl artifact put` with referrers can include annotations.
- `regctl image copy` with referrers points to the wrong manifest.
- Include referrers in pretty printers
- Set correct reference when copying
- Treat referrers as child objects before Refer is pushed
- Create artifacts with minimal refer descriptor (exclude annotations)
`regctl artifact put` and `regctl image copy` with experimental refers options should work according to OCI's WG proposal E.
E2e tests are still TBD. Documentation is not included for experimental features.
=> Bug fixes for referrers

cmd/regctl/artifact.go, cmd/regctl/manifest.go, docs/regctl.md, types/manifest/manifest.go, types/manifest/manifest_test.go
Related to #241 
This adds `--by-digest` to artifact and manifest put commands to push using a digest instead of a tag.
The media-type is now optional on a `manifest put` since that is automatically detected from the manifest body.
The put commands also support a format option to extract content from the pushed manifest.
```
$ echo hello | regctl artifact put --by-digest localhost:5000/artifact
sha256:9cd73ae83674712678356e7e820add0b7f492014bfdfe9db454c963f6c4640ae
$ regctl artifact get localhost:5000/artifact@sha256:9cd73ae83674712678356e7e820add0b7f492014bfdfe9db454c963f6c4640ae
hello
```
Allow pushing artifacts and manifest by digest.
=> Allow pushing a manifest by digest

config/credhelper.go, config/credhelper_test.go, config/docker.go, config/host.go, config/host_test.go, config/testdata/docker-credential-test, internal/auth/auth.go
Credential helpers should support the `<token>` user for an identity token, and also when extracting logins from the docker config. These should be used a refresh token when requesting a bearer token.
Authentication with tokens should work. I currently don't have access to any registries that use these.
=> Fix handling of tokens with credential helpers

config/docker.go, config/docker_test.go, config/testdata/docker-config.json
Fixes #245 
Loading of credential helpers did not account for names with schema's (https/http) and the Docker Hub `https://index.docker.io/v1/` entry. This normalizes the name to parse it the same in both the `auths` and `credHelpers` section of `~/.docker/config.json` file.
Use a `~/.docker/config.json` with a credential helper, e.g.:
```jsonc
cat ~/.docker/config.json
{
"credHelpers": {
"https://index.docker.io/v1/": "docker-hub"
}
}
```
Fix: credential helper for Docker Hub
=> Fix handling of Docker Hub with credential helper

cmd/regctl/config.go, cmd/regctl/registry.go, config/credhelper.go, config/credhelper_test.go, config/docker.go, config/docker_test.go, config/host.go, config/testdata/docker-config.json, config/testdata/docker-credential-test, regclient.go
Addresses #245 
Host entries are now parsed through the same method regardless of how they are loaded. And cred helpers should now be called with the original hostname, not the normalized name that strips off schemes and repositories.
A credential helper for docker hub defined in `~/.docker/config.json` should work.
Normalize parsing of registry names in various components.
=> Normalize host definition and fix cred helper

image.go, scheme/ocidir/referrer.go, scheme/ocidir/referrer_test.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go, types/referrer/referrer.go
Make the referrers listing more strict based on manifest media types and the tag regex. Also include the matching tags in the returned referrer list so a recursive image copy with digest tags can copy the tags not included as a referrer.
Copying an image with both a reference and a signature should work without modifying the signature tag and without duplicating manifest copies.
Exclude tags from referrers when copying digest tags.
=> Track tags used by refers

internal/reghttp/http.go
Auth requests are not handled with the same TLS settings as other registry requests. (See #251)
This moves to custom TLS logic for a host into the getHost method before the newAuth method is defined.
Access a registry with custom TLS settings and authentication required.
Fix handling of custom TLS settings on a registry with authentication
Unit or e2e testing with custom TLS in reghttp is still needed. This PR was verified with manual tests.
=> Move TLS logic to handle auth requests

cmd/regctl/artifact.go, types/ref/ref.go
`regctl artifact put --refers ...` now takes an argument, and the reference to push is now option to support pushing a refers entry. Either a reference to push or a refers reference is required, and pushing both is also supported.
```
echo "test" | regctl artifact put --refers ${image_name}
```
This feature is still considered experimental, so there are no tests or documentation provided.
=> regctl artifact put refer as arg

cmd/regctl/blob.go, docs/regctl.md
The format option for `regctl blob put` was not configurable and reused the `get` format. This change allows the field to be changed and defaults to showing just the digest for easier scripting.
`echo hello | regctl blob put ocidir://test --format '{{.Digest}} with {{.Size}} bytes'`
`regctl blob put` supports a format string.
=> Output digest on blob put, delay GC of blobs

cmd/regsync/regsync_test.go, cmd/regsync/root.go
On regsync server startup, this triggers an immediate sync for any missing tags on the target. Stale tags will be updated on the next timer cycle.
Run `regsync server -v debug` with a config and check for `target exists` lines for entries where the target exists but is stale.
regsync immediately syncs any tags missing on the target without waiting for first sync schedule
=> Copy missing tags on regsync server start

mod/mod_test.go, scheme/ocidir/referrer.go, scheme/reg/referrer.go, types/blob/common.go, types/manifest/manifest.go
Several manifest methods are redundant and can be removed.
Tools like staticcheck will report usage of deprecated methods.
Redundant manifest methods have been deprecated
=> Deprecating redundant methods

cmd/regbot/sandbox/image.go, cmd/regctl/artifact.go, cmd/regctl/image.go, image.go, mod/dag.go, scheme/ocidir/blob_test.go, scheme/ocidir/close.go, scheme/ocidir/manifest_test.go, scheme/reg/referrer.go, types/docker/schema2/manifestlist.go, types/manifest/docker1.go, types/manifest/docker2.go, types/manifest/manifest.go, types/manifest/manifest_test.go, types/manifest/oci1.go
This splits out Image and Index/ManifestList specific methods into separate interfaces. Set methods were also added for updating the config, layers, and manifests descriptors.
Old manifest methods will now be flagged as deprecated by staticcheck. Usage of the new `Set*` methods will be added in future PRs.
Manifest methods specific to Images and Indexes/ManifestLists have a different interface.
=> Separate manifest interfaces and add set methods

cmd/regctl/index.go, docs/regctl.md, image.go, scheme/ocidir/manifest.go, types/descriptor.go, types/descriptor_test.go
This adds a new `regctl index` command. This can be used to create or modify an OCI Index or Docker Manifest List.
Deleting a platform:
```
regctl image copy localhost:5000/regclient/regctl ocidir://testregctl
regctl manifest get ocidir://testregctl
regctl index del ocidir://testregctl --platform linux/s390x
regctl manifest get ocidir://testregctl
```
Adding `regctl index` command to create and mutate an Index or Manifest List
=> Add regctl index to create/mutate manifest lists

scheme/ocidir/manifest.go, scheme/ocidir/ocidir.go, scheme/ocidir/ocidir_test.go, scheme/ocidir/tag.go
Some tools creating an OCI Image Layout will output a full reference in the index.json annotation instead of just the tag.
If a full reference is included in the OCI Image Layout annotation, parse the tag from that reference in commands like tag list and manifest get.
`regctl tag ls ocidir://repo` and `regctl manifest get ocidir://repo` will work if repo contains a full reference instead of just the tag in the index.json annotation.
=> Support a full ref in the ocidir index annotation

image.go, types/ref/ref.go, types/ref/ref_test.go
An export from an ocidir of a single image cannot be loaded into docker because of an invalid reference.
This converts the reference to something resembling a registry reference when exporting the docker specific manifest.
```
regctl image export ocidir://path file.tar
docker load <file.tar
```
Fix reference for ocidir exports for importing into docker
=> Use a registry like reference in docker export

internal/auth/auth.go, internal/auth/auth_test.go
https://datatracker.ietf.org/doc/html/rfc7235#section-2.1
Fixes #265 
The auth header parsing should accept bare token characters without a quote, in addition to the alpha-numeric characters.
Perform authenticated requests with a realm set to `/` without quotes.
Fix support for authentication parsing of token characters without quotes.
=> Include various token characters from rfc7235

cmd/regctl/blob.go, cmd/regctl/manifest.go, docs/README.md, docs/regctl.md, internal/diff/diff.go, internal/diff/diff_test.go, internal/diff/myers.go, types/blob/blob_test.go, types/blob/reader.go, types/blob/tar.go
This adds the ability to diff manifests, configs, and layers.
```shell
$ regctl manifest diff alpine:3.13 alpine:3.14
@@ -1,7 +1,7 @@
{
"manifests": [
{
-       "digest": "sha256:25b013fc42c0f7d8a16f01b30206db14356f0e0faf631699e06b5eab4450e31a",
+       "digest": "sha256:a573d30bfc94d672abd141b3bf320b356e731e3b1a7d79a8ab46ba65c11d79e1",
"mediaType": "application\/vnd.docker.distribution.manifest.v2+json",
"platform": {
"architecture": "amd64",
@@ -10,7 +10,7 @@
"size": 528
},
...
$ regctl manifest diff \
alpine@sha256:25b013fc42c0f7d8a16f01b30206db14356f0e0faf631699e06b5eab4450e31a \
alpine@sha256:a573d30bfc94d672abd141b3bf320b356e731e3b1a7d79a8ab46ba65c11d79e1
@@ -4,7 +4,7 @@
"config": {
"mediaType": …
```
=> Adding diff and regctl cmds to compare manifests and blobs

cmd/regctl/artifact.go, scheme/ocidir/referrer.go, scheme/ocidir/referrer_test.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go, scheme/scheme.go
This adds the ability to filter artifacts from the experimental artifact list methods. It's implemented in `regctl artifact get` and `regctl artifact list`
```
$ regctl artifact list ocidir://testrepo:latest
Refers:         ocidir://testrepo:latest
Referrers:      
Name:         ocidir://testrepo@sha256:5cc04f2ae7ef200ad5f743f2dc5a92db055d5fb133fb92a2b10c5e58e12c429e
Digest:       sha256:5cc04f2ae7ef200ad5f743f2dc5a92db055d5fb133fb92a2b10c5e58e12c429e
MediaType:    application/vnd.oci.image.manifest.v1+json
ArtifactType: application/vnd.unknown.config.v1+json
Annotations:  
hello:      world
$ echo "hi OCI" | regctl artifact put --refers ocidir://testrepo:latest --annotation hello=OCI
$ regctl artifact list ocidir://testrepo:latest
Refers: …
```
=> Add filtering for artifact referrers

internal/httplink/httplink.go, internal/httplink/httplink_test.go, scheme/reg/tag.go, scheme/reg/tag_test.go, types/ref/ref.go, types/tag/taglist.go, types/tag/taglist_test.go
Fixes #274 
When the link header is seen when reading tag lists, the next link is followed and multiple pages will be assembled until the limit is reached.
```
regctl tag ls quay.io/calico/node
```
Support Link header in tag pagination seen on quay.io
=> Support Link header in tag pagination

internal/auth/auth.go, internal/auth/auth_test.go
The user-agent header in auth requests was defaulting to the Go user agent.
This updates the user-agent header in auth requests to match other HTTP requests.
Check the headers on auth requests by sniffing the network traffic or server logs.
=> Include user-agent header in auth requests

cmd/regctl/artifact.go, cmd/regctl/manifest.go, image.go, internal/reqresp/reqresp.go, manifest.go, manifest_test.go, mod/dag.go, referrer.go, scheme/ocidir/manifest.go, scheme/ocidir/referrer.go, scheme/ocidir/referrer_test.go, scheme/reg/manifest.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go, scheme/scheme.go, types/docker/schema2/manifest.go, types/manifest/docker2.go, types/manifest/manifest.go, types/manifest/manifest_test.go, types/referrer/referrer.go
This refactors the referrers support. Updates to the referrers list are handled with `ManifestPut` and `ManifestDelete` directly, instead of requiring a separate `ReferrersPut`. This also adds support for the newer referrers endpoint that OCI is expected to be approved soon.
```
echo hello | regctl artifact put --annotation hello=world --refers $image
regctl artifact list $image
regctl artifact get $artifact_name
```
Update refers support for current OCI PR and support delete.
Breaking: `regclient.ManifestWithDesc` has been renamed to `regclient.WithManifestDesc`
Breaking: `manifest.Referrer` interface has been renamed to `manifest.Refers`
Breaking: `ReferrerPut` method has been removed, use `ManifestPut` instead
Breaking: …
=> Refactoring referrers support

cmd/regctl/main.go, docs/README.md
This adds a tip to the error message when querying an HTTP registry without disabling TLS.
```shell
$ regctl manifest get 127.0.0.1:5000/library/alpine
WARN[0000] Sleeping for backoff                          Host="127.0.0.1:5000" Seconds=1.999998004
WARN[0002] Sleeping for backoff                          Host="127.0.0.1:5000" Seconds=3.999992055
failed to get manifest 127.0.0.1:5000/library/alpine:latest: Get "https://127.0.0.1:5000/v2/library/alpine/manifests/latest": http: server gave HTTP response to HTTPS client
Try updating your registry with "regctl registry set --tls disabled <registry>"
```
regctl: add tips to common errors
=> regctl: Add tips on common errors

.github/workflows/docker.yml, .github/workflows/go.yml, blob_test.go, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit, cmd/regctl/manifest.go, config/credhelper_test.go, config/host_test.go, go.mod, image.go, internal/auth/auth.go, internal/reghttp/http.go, internal/reqresp/reqresp.go, internal/retryable/retryable.go, internal/wraperr/error.go, pkg/template/template.go, regclient.go, scheme/ocidir/ocidir.go, scheme/reg/blob.go, scheme/reg/blob_test.go, scheme/reg/repo.go, scheme/reg/tag.go, types/blob/reader.go, types/blob/tar.go
This bumps Go to 1.19 and several Github Actions versions. Deprecated methods from `ioutil` were fixed.
No visible change, nothing should break.
Upgrade to Go 1.19
=> Bumping to Go 1.19 and GHA versions

types/descriptor.go, types/descriptor_test.go
When descriptors change the media type for OCI, the `Same` comparison should still match.
Compare two descriptors with the media type changed for OCI.
Descriptor comparison now allows for Docker to OCI conversion.
=> Descriptor compare allows OCI conversion

cmd/regbot/regbot_test.go
Fixes #297
The regbot test should not depend on the local platform. This fetches a specific platform manifest.
`go test ./cmd/regbot`
Fixing regbot tests to run on other platforms
=> Do not depend on local platform for regbot tests

types/manifest/manifest.go, types/manifest/manifest_test.go, types/platform/platform.go, types/platform/platform_test.go
When fetching the local platform on mac or windows, this will fail even when Linux images are available for those architectures.
This adds a second comparison for compatible platforms and a fall back query for manifest lists. The exact match is still preferred, and the fall back is only used when an exact match cannot be found.
```
regctl manifest get alpine --platform darwin/amd64
```
Fallback to using linux platforms on mac and windows when querying manifest lists
=> Fallback to linux platforms for mac and windows

.dockerignore, .github/workflows/docker.yml, .gitignore, Makefile, cmd/regbot/embed/.git-keep, cmd/regbot/root.go, cmd/regctl/embed/.git-keep, cmd/regctl/root.go, cmd/regsync/embed/.git-keep, cmd/regsync/root.go, embed/.git-keep, internal/version/version.go, internal/version/version_buildinfo.go, internal/version/version_old.go, internal/version/version_test.go, regclient.go
Fixes #304 
This removes the `embed/version.json` and associated calls, replacing with `runtime/debug` calls.
```
$ regctl version 
VCSRef:     89bfc2db3b9eca816c970af951b0a5db7a7f7d3f     
VCSCommit:  89bfc2db3b9eca816c970af951b0a5db7a7f7d3f  
VCSState:   clean                               
VCSDate:    2022-09-21T00:10:00Z   
Platform:   linux/amd64                       
GoVer:      go1.19                                
GoCompiler: gc    
```
Breaking: tag details are no longer available in version commands.
Breaking: `regclient.VCSRef` and `VCSTag` variables removed.
Breaking: detailed version support removed for Go 1.17 and earlier.
=> Using runtime/debug for git version details

.github/workflows/docker.yml, .gitignore, Makefile, build/oci-image.sh
This dogfoods regclient during the image build to backdate timestamps to the commit time and add various annotations with `regctl image mod`.
Unfortunately, this needs to be tested in prod after the merge.
Make image builds reproducible
=> Make image builds reproducible

.github/workflows/docker.yml, build/oci-image.sh
This is needed for reproducibility since caching will pull in stale timestamps.
Builds are reproducible yet. Labels didn't match between the local and GHA builds, and layers had timestamps from cached builds.
This disables build caching and aligns the labels in the GHA and local builds.
Ideally, the images on the registry will be able to be reproduced with `make oci-image`.
=> Disable build caching and align labels

.github/workflows/docker.yml
GHA had a typo on the output parameter for the docker build.
output -> outputs
GHA for docker builds should succeed after merging.
=> Fixing GHA error in docker build

.dockerignore, .github/workflows/docker.yml
This fixes a few more reproducibility issues with the docker image:
- Local images should not build using the vendor folder.
- GHA build should use the https:// rather than git:// directory.
- GHA build should use the git commit timestamp.
Added the vendor folder to `.dockerignore`. And adjusted how a few labels were set in the docker image build.
Images built locally and in GHA should have a matching digest.
=> Fix a few more reproducibility issues

build/oci-image.sh
This fixes a small typo in `oci-image.sh` that caused the local image build to have the wrong label.
Typo fix.
GHA docker images and locally build images should have the same digest.
=> Fixing image.version label on local builds

Makefile
The regbot image was not reproducible.
This sets `buildid` to an empty string in the binary.
```
make oci-image-regbot
regctl image digest ocidir://output/regbot:scratch
regctl image digest ocidir://output/regbot:scratch
```
The above digests should match:
```
regctl image digest ghcr.io/regclient/regbot:edge
regctl image digest ghcr.io/regclient/regbot:edge-alpine
```
=> Strip buildid from binaries to reproduce regbot

cmd/regctl/artifact.go, types/oci/v1/artifact.go
Fixes #326 
`artifactType` is optional for the artifact media type.
Pushing an artifact media type no longer includes an `artifactType` by default.
```
$ echo test | regctl artifact put \
--media-type application/vnd.oci.artifact.manifest.v1+json \
ocidir://test:artifact1
$ echo test | regctl artifact put \
--artifact-type application/example.test.text \
--media-type application/vnd.oci.artifact.manifest.v1+json \
ocidir://test:artifact2
$ echo test | regctl artifact put \
--artifact-type application/example.test.text \
--media-type application/vnd.oci.image.manifest.v1+json \
ocidir://test:artifact3
$ regctl manifest get ocidir://test:artifact1 --format '{{jsonPretty .}}'
{
"mediaType": "application/vnd.oci.artifact.manifest.v1+json", …
```
=> Make artifactType optional

cmd/regbot/internal/go2lua/import.go, cmd/regbot/sandbox/repo.go, docs/regbot.md
Fixes #329 
Adds options to `repo.ls` that takes a table with `limit` and `last`.
Example config yaml:
```yml
version: 1
creds:
- registry: localhost:5000
tls: disabled
scripts:
- name: repo ls opts
script: |
reg = "localhost:5000"
list = repo.ls(reg, {limit = 10, last = "library/busybox"})
for k, i in ipairs(list) do
log(k .. ": " .. i)
end
```
regbot: adding options to `repo.ls` to support paginated responses
Testing for regbot uses ocidir where paginated `repo.ls` doesn't apply. These changes have been manually tested and will eventually be rolled into an e2e test suite.
=> regbot: add limit and last options to repo.ls

blob_test.go, internal/reghttp/http.go, internal/reghttp/http_test.go, internal/reqresp/reqresp.go
This should help with #331 
Registry calls did not have a Seek method defined which prevented reusing the blob reader for retries. This adds the Seek, and adds testing with failed connections.
A blob copy on problematic networks should recover from errors, and give better debug logging.
Improve retries of blob copies between registries
=> Adding Seek to reghttp to enable retries

types/blob/blob_test.go, types/blob/tar.go
Trying to read a file from an image built by ko fails because of leading slashes in the filenames.
This normalizes the filename for both the file being searched and each tar entry.
```
regctl image get-file ghcr.io/sigstore/cosign/cosign:v1.13.1 /ko-app/cosign >cosign
```
=> Normalize filenames on tar read

types/error.go, types/manifest/common.go, types/manifest/docker1.go, types/manifest/docker2.go, types/manifest/manifest.go, types/manifest/manifest_test.go, types/manifest/oci1.go
Various methods would falsely succeed when a manifest is defined only with a HEAD request.
Check if the manifest "isSet" before attempting to return content.
`ManifestHead` + `Get*` methods will fail with an `ErrManifestNotSet`
Fix error handling on manifests created by `ManifestHead`
=> Check if manifest is set

build/oci-image.sh, mod/dag.go, mod/mod.go, mod/mod_test.go
Docker's buildkit attestations are attached within the index, but are artifacts rather than images with layers. This breaks the `regctl image mod` command, which also breaks CI.
Image mod now checks for supported layer and config media types before processing.
Perform a `regctl image mod` on an index that contains docker's buildkit attestations with a timestamp change to the layer contents.
Fix `regctl image mod` for non-tar layers and non-image configs.
=> Fix handling of non-tar layers

.github/workflows/docker.yml, build/oci-image.sh
Image builds aren't reproducible.
Converts docker provenance to OCI referrers in GHA builds.
Digests should match GHA using `make oci-image`
Fix reproducible builds with docker provenance.
=> Use OCI referrers in the docker image build

.github/workflows/docker.yml, .github/workflows/go.yml, Makefile, build/oci-image.sh
This adds the creation of SBOMs to the artifacts and images. Both CycloneDX and SPDX formats are generated in JSON.
```
make artifacts
```
and with images:
```
regctl artifact list  ocidir://output/regctl@$(regctl image digest --platform local ocidir://output/regctl:scratch)
regctl artifact get --subject ocidir://output/regctl@$(regctl image digest --platform local ocidir://output/regctl:scratch) \
--filter-artifact-type application/spdx+json
```
Add SBOMs to artifacts to images
=> Add SBOMs to artifacts and images

.github/workflows/docker.yml
Pushing manifests with a `subject` field to Hub is currently resulting in a 404. This removes any referrers from a push to Hub as a workaround for https://github.com/docker/hub-feedback/issues/2307.
This modifies the GHA to skip pushing referrers to Hub.
CI will hopefully unbreak.
=> Disable pushing referrers to Hub in GHA

image.go, image_test.go, internal/rwfs/mem.go
Fixes #354
This runs filenames from tar through filepath.Clean to normalize the input.
1. create an OCI image tarball with `regctl image export $image $file`
2. extract the tar into a directory with `tar -xvf $file -C $dir`
3. re-archive the tar: `tar -cf $file -C $dir .`
4. run `regctl image import $image $file`
Fix issue importing images created with `tar`.
=> Normalize filenames on tar import

cmd/regctl/artifact.go, scheme/ocidir/referrer.go, scheme/ocidir/referrer_test.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go, scheme/scheme.go
This adds a platform option to the referrers list API, and platform options to the `regctl artifact` commands.
```
$ regctl artifact list ghcr.io/regclient/regctl:edge --platform local
Subject:                                     ghcr.io/regclient/regctl:edge
Referrers:                                   
Name:                                      ghcr.io/regclient/regctl@sha256:5ff1e4b783ebc265fdf307b2b6acf16209f0d56eff66775a46996f3925e1030c
Digest:                                    sha256:5ff1e4b783ebc265fdf307b2b6acf16209f0d56eff66775a46996f3925e1030c
MediaType:                                 application/vnd.oci.image.manifest.v1+json
ArtifactType:                              application/vnd.oci.image.config.v1+json
Annotations: …
```
=> Adding platform option to artifact commands

cmd/regctl/artifact.go, cmd/regctl/artifact_test.go, cmd/regctl/main_test.go, docs/regctl.md, scheme/ocidir/referrer.go, scheme/ocidir/referrer_test.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go
This adds a `regctl artifact tree` command to visualize multiple levels of artifacts.
```
$ regctl artifact tree ghcr.io/regclient/regctl:edge
Ref: ghcr.io/regclient/regctl:edge
Digest: sha256:87f3d11f446a99648d958e031deec4989dcb1c5f199c4c72e7b3ead8910ea89f
Children:
- sha256:6be79745a8eec215eb1f9a4ab86b5b1f3fb80659f443f0b85821037b9477b616 [linux/386]
Referrers:
- sha256:81e9a3c4c15a667d58c3a534bb9602726c45f86620f6bb04d2425c7e3712ca90: application/vnd.oci.image.config.v1+json
- sha256:fbf23884449599649006ed8782edbb2fcda80b8182a015d11fac55acdf904990: application/vnd.cyclonedx+json
- sha256:1cc3b61e166ed96d12c7fc3dd83c55e3928a9bd8050a7ad808586851086f2f38: application/spdx+json
- sha256:e51e7e4e051d06d21f3de3947b4d3db4f741b4b18a47d37bd6e6290945894d5c [linux/amd64]
Referrers:
- …
```
=> Adding regctl artifact tree

cmd/regctl/artifact.go, cmd/regctl/index.go, cmd/regctl/manifest.go, cmd/regctl/manifest_test.go, cmd/regsync/root.go, image.go, manifest.go, manifest_test.go
Some registries are missing the docker digest header.
This triggers a fallback to a GET request on those registries.
```
regctl image digest registry.redhat.io/rhel8/buildah:8.7
```
Fallback to GET when HEAD request is missing digest header
=> Fallback from head to get when digest is missing

.version-bump.lock, .version-bump.yml, Makefile
Staticcheck will break old versions of Go in new releases.
Pin the version of staticcheck so that Go and staticcheck are upgraded together. This also pins the version of Syft.
```
make lint
```
Pin the version of staticcheck.
=> Pin version of staticcheck and syft

.github/workflows/docker.yml, .github/workflows/go.yml, .version-bump.lock, .version-bump.yml
This adds signing to the binary artifacts using cosign's keyless method.
This also added entries for Syft and Go in the version-bump config.
`metadata.tgz` will be shipped with artifacts with a `.sig` and `.pem` that can be used with `cosign verify-blob`.
Binary artifacts are signed with cosign keyless signing.
=> Add keyless signing for binary artifacts

blob_test.go, manifest_test.go, mod/dag.go, types/descriptor.go, types/descriptor_test.go
The data field was being double base64 encoded.
Removes the extra base64 encoding, depending on the json encoding of the byte field.
```
regctl image mod $src --data-max 2000 --create $dest
regctl manifest get $dest --format '{{jsonPretty .}}'
```
Fix handling of data field
=> Fix handling of data field

cmd/regctl/artifact.go, types/manifest/oci1.go, types/mediatype.go, types/oci/v1/artifact.go
OCI is delaying the release of the artifact manifest and it may change in the future.
This marks the artifact manifest as experimental and hides flags that exposed it.
```
$ regctl artifact put --help
... does not show --media-type ...
$ echo test | regctl artifact put --media-type application/vnd.oci.artifact.manifest.v1+json --artifact-type application/vnd.example.test localhost:5000/artifact:test-oci-artifact
WARN[0000] changing media-type is experimental and non-portable
failed to put manifest localhost:5000/artifact:test-oci-artifact: request failed: unexpected http status code: Bad Request [http 400]: {"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}
```
The warning was added to indicate the flag is unsupported, and the failure is expected on …
=> Artifact manifest is experimental

cmd/regctl/index.go, cmd/regctl/index_test.go
Fixes #294
This adds a platform option to `regctl index create` and `regctl index add`.
```
regctl index create \
--ref ${src} \
--platform linux/amd64 \
--platform linux/arm64 \
${tgt}
regctl index add \
--ref ${src} \
--platform linux/arm/v7 \
--platform linux/arm/v6 \
${tgt}
```
Add platforms option to `regctl index add/create`
=> Add platform option to regctl index create/add

cmd/regctl/image.go, mod/manifest.go, mod/mod_test.go
This adds a flag `regctl image mod --to-docker` to convert manifests from OCI to Docker schema2 types. This is used to support old installs of the Docker engine.
```
regctl image copy ubuntu $tgt
regctl image mod $tgt --to-docker --replace
```
Adding `regctl image mod --to-docker` to convert manifests from OCI to Docker schema2
=> Adding image mod to-docker

internal/auth/auth.go, internal/auth/error.go, internal/reghttp/http.go, internal/reghttp/http_test.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go
Fixes #384
Harbor responds with an unauthorized rather than not found to the referrer API. This ignores those errors.
It also removes the `_oci/artifacts` API fallback from referrer the development work, and cleans up auth error handling.
Actions against a Harbor registry that call the referrers API won't trigger backoffs or output warnings.
Improve handling of the referrers API with Harbor
=> Fix referrer handling of auth response

Makefile, internal/version/version.go, internal/version/version_buildinfo.go, internal/version/version_old.go
Fixes #383 #386
This manually injects the git tag into builds when available.
`regctl version` will output a tag on the next tagged release. Until this, it will indicate `(devel)` for an untagged release.
Include tag in the version output
=> Include tag in the version output

cmd/regbot/config.go, cmd/regbot/root.go, cmd/regctl/config.go, cmd/regctl/config_test.go, cmd/regctl/root.go, cmd/regsync/config.go, cmd/regsync/root.go, regclient.go, regclient/regclient.go, scheme/reg/blob.go, scheme/reg/blob_test.go, scheme/reg/reg.go
This adds support for the `OCI-Chunk-Min-Length` header defined in https://github.com/opencontainers/distribution-spec/pull/391
Performing a chunked upload to a registry that uses this header, with a small chunk size, will automatically adjust as long as the chunk size doesn't exceed the limit.
- Support `OCI-Chunk-Min-Length` header
=> Allow registry to adjust blob chunk size

scheme/reg/tag.go, scheme/reg/tag_test.go, types/descriptor.go
This should solve #393.
The temporary manifest used to purge a tag needs a layer for for some registries to allow it.
`regctl tag rm` on certain registries.
- Fix an issue on `regctl tag rm` to support registries that require a layer
=> Include a scratch layer in the fallback tag delete

mod/manifest.go
Changing the config mediaType blindly can break artifacts.
This checks the config mediaType for a known good value before changing it.
Converting an artifact with a custom config mediaType should not change the value.
- Image mod only convert `config.mediaType` between known values
=> Only change config media type from known values

scheme/reg/blob.go
Fixes #398
Some registries fail on an anonymous blob mount instead of defaulting to a 202 response. This ignores those errors instead of triggering the backoff code. The errors are already ignored at higher levels since a failure to run the blob mount is followed by the slower blob upload.
Pushing images and deleting tags on certain versions of quay.io will stop triggering backoffs.
- Ignore anonymous blob mount failures
=> Ignore anonymous blob mounts failures

config/credhelper.go, config/docker.go, config/docker_test.go, config/testdata/config.json, config/testdata/docker-credential-test, config/testdata/docker-credential-teststore
Fixes #403. The handling of docker's credStore assumed there would be empty auths entries, rather than fetching the list from the credential helper.
This makes a best effort to get the list from the helper. Error handling and logging of issues is minimal to avoid a bad `docker/config.json` breaking the regclient commands.
Running binaries on Docker Desktop should detect docker logins.
- Fix handling of docker registry logins with credStore
=> Fix support for docker credsStore

cmd/regsync/root.go
Fixes #404.
The regsync for an entire registry did not handle the scenario when the catalog API paginated the responses. This now loops through the paginated responses when syncing a registry.
Use regsync on a registry with more repositories than the default catalog API response and verify all repos gets synced.
- Fix regsync handling of the paginated repo listing when syncing registries
=> regsync handle repo list exceeding catalog limit

blob_test.go, cmd/regbot/root.go, cmd/regctl/root.go, cmd/regsync/root.go, manifest_test.go, regclient.go, regclient/regclient.go
With the addition of the WithRegOpts option, several other options can be deprecated.
Linting will trigger issues when deprecated methods are used.
- Deprecated: `regclient.WithConfigHosts` is replaced by a variadic on `regclient.WithConfigHost`
- Deprecated: `regclient.WithBlobLimit`, `regcleint.WithBlobSize`, `regclient.WithCertDir`, `regclient.WithRetryDelay`, and `regclient.WithRetryLimit` are replaced by `regclient.WithRegOpts`
=> Deprecate redundant regclient options

regclient.go, regclient_test.go
Fixes #410
The input validation was done on the wrong variable resulting in WithRegOpts always returning without making changes.
`regclient.WithRegOpts` should now work.
=> Fix regclient.WithRegOpts

cmd/regctl/artifact_test.go, cmd/regctl/manifest_test.go, cmd/regsync/regsync_test.go, types/error.go, types/ref/ref.go, types/ref/ref_test.go
A reference with multiple consecutive separators in a path component is invalid.
The regex was adjusted to remove the `*` so that the separator cannot appear consecutively.
Unallowed:
- `example.com/path--part:tag`
- `example.com/path._part:tag`
Allowed:
- `example.com/path.and_part:tag`
Invalid references return an invalid reference error without sending the request to the registry (where a 404 would typically be received).
Fix: invalid references are detected before querying the registry
=> Fix handling of multiple separators in a reference

CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md
Linting now requires email addresses to be quoted.
Email addresses in markdown files are now quoted. Contact details for CoC and security were also updated.
GHA linting checks should pass.
=> Quote email addresses for linting

scheme/reg/manifest.go, scheme/reg/referrer.go, scheme/reg/repo.go, types/blob/reader.go, types/manifest/manifest.go, types/mediatype.go, types/mediatype_test.go, types/tag/taglist.go
Fixes #417
The content-type headers from some registries contain optional parameters, and can be in upper case. This normalizes the result to only the base value in lower case.
It also updates the manifest get request to accept the OCI artifact manifest. Support for this should still be considered experimental until released by OCI.
Notation signed content on ACR should be accessible with `regctl artifact list` and `regctl manifest get`.
- Fix handling of content-type headers.
- Accept manifests with OCI artifact media type (experimental).
=> Fix parsing of media types

internal/rwfs/mem.go, internal/rwfs/os.go, internal/rwfs/rwfs.go, internal/rwfs/rwfs_test.go
This adds a Stat implementations to os and mem in rwfs.
=> Add stat interface to rwfs

scheme/reg/referrer.go, scheme/reg/reg.go
Copying an image with referrers may encounter a race condition updating the fallback tag.
This locks the update of the fallback tag to avoid internal race conditions. External race conditions are still possible.
Copying an image with referrers should have all the referrers in an artifact list of the destination.
Avoid an internal race condition when managing the referrers fallback tag.
=> Avoid a race condition when updating referrers

internal/rwfs/rwfs.go, scheme/ocidir/blob.go
This removes the in memory digest calculation.
Pushing a blob to an ocidir without a digest uses a memory buffer.
Since there was already a tmpfile being used for safely writing blobs, this was also used for blobs that did not have a predefined digest.
No user visible changes other than less memory usage in some scenarios.
=> Blob put for ocidir uses tmp file

cmd/regbot/regbot_test.go, cmd/regbot/root.go, cmd/regbot/sandbox/image.go, cmd/regbot/sandbox/sandbox.go
Semaphore isn't needed for a basic throttle.
This removes an external dependency. The semaphore was excessive for this use case, a buffered channel (the throttle) is good enough.
No user visible change.
=> Switch regbot from semaphore to throttle

.version-bump.yml, Makefile
Markdown lint was not pinned, resulting in stale images used on machines that had previously pulled the image.
This pins the markdown lint image to a specific version tag.
```
make lint-md
```
=> Pinning markdown lint version

types/blob/reader.go
A deadlock can occur when reading too many configs (e.g. `regctl image mod` on a multi-platform image).
This closes the blob reader when converting it to a config.
`regctl image mod` on an image with lots of platforms does not deadlock.
Fix: close reader when converting a blob to an OCI config
=> Close blob reader when converting to a config

types/manifest/manifest.go, types/manifest/manifest_test.go
Manifests without a mediaType can't be processed from sources without a descriptor or http header that includes the mediaType.
This evaluates the manifest with duck typing, looking for manifests or layers, and the media types inside the first descriptor to decide if it's a Docker or OCI image or index.
Fetching the manifest by digest from an OCIDir should not fail even if the manifest mediaType is missing.
Support manifests missing a mediaType field.
=> Support OCI manifests without mediaType

cmd/regctl/image.go, mod/config.go, mod/dag.go, mod/layer.go, mod/manifest.go, mod/mod.go, mod/mod_test.go
Fixes #433
This reworks image mod to directly copy to the target reference instead of working within the source repo. It also pushes directly to the requested tag to workaround a bug in quay.
The following does not require write access to Docker Hub:
```
regctl image mod debian:8 --to-oci --create localhost:5000/library/debian:8-oci
```
Image mod pushes directly to the target ref without an extra copy step
=> Push directly to target ref in image mod

cmd/regctl/image.go, cmd/regsync/config.go, cmd/regsync/regsync_test.go, cmd/regsync/root.go, docs/regsync.md, image.go, image_test.go
Copying with digest tags and referrers needs to check all manifests for those digest tags and referrers. If that content does not change from the source image, this is a lot of overhead.
This adds a fast check option to skip the referrers and digest tag checks when the manifest is already found at the destination.
```
regctl image copy --fast --referrers --digest-tags $src $dest
```
Add a fast check option for copying images with referrers and digest tags.
=> Add a fast copy option

cmd/regsync/regsync_test.go, cmd/regsync/root.go
The various actions in regsync should be differentiated using an enum rather than strings.
=> Chore: switching from strings to an enum

scheme/reg/manifest.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go, scheme/reg/reg.go
Copying a multi-platform image results in a lot of failed referrer API calls to OCI v1.0 registries.
Use the OCI-Subject header to know when the referrers API is supported. Cache the result of an API ping to avoid retrying it.
Referrers should still work, but commands pushing or listing referrers should run faster to OCI v1.0 registries.
Handle the OCI-Subject header to detect referrer support.
=> Reduce referrer API calls

cmd/regctl/image.go, internal/units/size.go, internal/units/size_test.go
The progress line doesn't differentiate between manifests and blobs very well, and the bandwidth isn't useful if much of the work is round trips that aren't counted.
Separate the manifests, blobs, and add an elapsed time. This also switches human readable numbers to a fixed width to avoid the display jumping every time the number ends with a 0 in the decimal.
Output from:
```
regctl image copy $src $dst
```
should be easier to follow.
Update `regctl image copy` for tty displays.
=> Adjust progress display of image copy

cmd/regctl/artifact.go, scheme/reg/referrer.go
Debugging output is overly verbose when copying referrers on some registries that don't support referrers.
There's an unneeded manifest head request on the artifact tree command.
- Remove debugging on referrer API failure, this can be overly verbose on some registries.
- Set the digest for for a given ref in artifact tree to avoid an extra HEAD request.
Debugging output should be cleaner in commands like `artifact tree`.
=> Referrers chores

cmd/regbot/config.go, cmd/regctl/registry.go, cmd/regsync/config.go, config/host.go, config/host_test.go, docs/regbot.md, docs/regsync.md, internal/reghttp/http.go
Fixes #450.
This adds support for client keys/certs needed for mTLS authentication.
1. Setup a registry with mTLS authentication. With `registry:2`, this can be done with the `REGISTRY_HTTP_TLS_CLIENTCAS` setting.
2. `regctl registry set --client-cert "$(cat client.pem)" --client-key "$(cat client.key)" $registry`
3. For regsync and regbot, there are `clientCert` and `clientKey` fields per host now. These can be set with Go templates, same as the `regcert` field.
Support client certs and keys for mTLS registry auth.
=> Support client certs for mTLS registry auth

.version-bump.lock, .version-bump.yml, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
GCR doesn't build correctly against the master branch.
Fixes #453.
This pins to a version and injects that version in the go build.
Ideally this will be fixed upstream to allow `go install` to work again.
```
$ docker run regclient/regctl:alpine /usr/local/bin/docker-credential-gcr version
Google Container Registry Docker credential helper v2.1.8
```
Fix GCR credential helper to work on Artifact Registry
=> Pin GCR helper to a tag

scheme/reg/tag.go, types/oci/v1/config.go
Embed the Platform field directly in the `ImageConfig`, rather than including the individual Platform components.
This aligns with the upstream OCI spec, and makes it easier to extract the platform from an image config.
Any code that initializes the ImageConfig may need a minor change.
No user visible changes in the CLIs.
regclient: embed the `Platform` field directly in the `ImageConfig`
=> OCI embedded Platform in the image config

.github/workflows/docker.yml, build/oci-image.sh, cmd/regctl/image.go, docs/regctl.md, mod/dag.go, mod/manifest.go, mod/mod_test.go, types/manifest/docker2.go, types/manifest/manifest_test.go, types/manifest/oci1.go
Platform specific manifests are missing annotations after a regctl image mod.
This adds the ability to configure annotations on individual platforms, all manifests, or only the index, in the multi-platform manifest.
The reproducible image build has the following example to update all manifests (using `[*]`):
```
regctl image mod \
"ocidir://output/${image}:${release}" --replace \
--to-oci-referrers \
--time-max "${vcs_date}" \
--annotation "[*]oci.opencontainers.image.created=${vcs_date}" \
--annotation "[*]oci.opencontainers.image.source=${vcs_repo}" \
--annotation "[*]oci.opencontainers.image.revision=${vcs_sha}"
```
Individual platforms can be modded using:
```
regctl image mod --annotation "[linux/amd64,linux/arm64]name=value" ...
```
Support updating annotations on platform specific …
=> Mod annotations on platform manifests in an index

image.go
Copying an image with referrers and digest-tags fails when trying to copy the fallback tag.
Fix the check when copying digest-tags to skip the referrers fallback tag.
```
regctl image copy --referrers --digest-tags ghcr.io/regclient/regctl:edge localhost:5000/regclient/regctl:edge
```
Fix copy when both referrers and digest-tags are included.
=> Fix copy with referrers and digest tags

.github/workflows/docker.yml, Makefile, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit, build/oci-image.sh
This leverages the `SOURCE_DATE_EPOCH` build arg that's now being supported by buildkit, removing some of the variability in the builds. It also removes the "dev" build stage to simplify the Dockerfiles. To speed up the builds, vendoring is run separate before the compile so that it's cached more often.
This also removes the temporary workaround from GCR credential helper install.
Use `SOURCE_DATE_EPOCH` build arg support in buildkit.
=> Cleanup docker image builds

Makefile, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
This fixes the broken build from the Dockerfile cleanup.
I broke the build.
This fixes GHA. `go mod vendor` doesn't work on an empty directory like `go mod download` does. And the `@` in the Makefile needs to be on the first line.
GHA will be unbroken.
=> Fixes for Makefile and Dockerfiles

image.go, types/error.go
The level check from before would return before the manifest was copied. This would break on registries that validate the manifest content already exists (most registries).
This looks for loops in direct parents, and if encountered, it switches to copy the referrers and digest tags after the manifest is pushed. The manifest wait group is being removed to reduce complexity and remove deadlock issues.
I'm looking at adding a priority queue alternative to the simple throttle that would make it more likely for all manifests to be queries before blob pulls so the interactive UX shows MB remaining with the total value sooner.
```
regctl image copy --digest-tags ghcr.io/sudo-bmitch/oci-sandbox:loop localhost:5001/oci-sandbox:loop
```
Fix handling of copy with looping referrers or digest-tags to …
=> Rework the loop detection/handling

types/manifest/manifest_test.go, types/manifest/oci1.go, types/oci/v1/index.go, types/referrer/referrer.go, types/referrer/referrer_test.go
OCI Index needs to support artifactType and subject.
OCI has added these features recently, so they now need to be supported here:
- https://github.com/opencontainers/image-spec/pull/1020
- https://github.com/opencontainers/image-spec/pull/1066
- https://github.com/opencontainers/image-spec/pull/1077
This updates the subject support to align with the Image manifest, and updates the pretty printer. Some of the tests were already being done by the loop test.
```
regctl manifest get ghcr.io/sudo-bmitch/oci-sandbox:loop
```
Support artifactType and subject fields on OCI Index
=> Add artifact support to OCI Index

cmd/regctl/tag.go, cmd/regctl/tag_test.go
Fixes #469
This adds filtering options to the `regctl tag ls` command. Both `--include` and `--exclude` are supported and can be passed multiple times.
```
regctl tag ls ghcr.io/regclient/regctl --exclude 'sha256-.*' --exclude 'buildcache.*'
regctl tag ls ghcr.io/regclient/regctl --include 'v\d+.*' --exclude '.*-alpine'
```
Add regctl tag list filtering
=> Add regctl tag list filtering

types/descriptor.go, types/manifest/oci1.go, types/oci/v1/artifact.go, types/oci/v1/config.go, types/oci/v1/manifest.go
The OCI descriptor requires mediatype, size, and digest.
- Descriptor fields mediatype, size, and digest are no longer omitted if empty.
- Refers field is no longer needed, replaced by subject.
- Docker specific config settings are added for showing docker images.
- Annotations should be after the subject field.
Fields like shell and healthcheck are now shown with:
```
regctl image config $img
```
- Chore: sync OCI types to align with upstream sources.
=> Adjust OCI types with upstream

types/ref/ref.go, types/ref/ref_test.go
OCI allows multiple `-`'s in repo names.
See https://github.com/opencontainers/distribution-spec/pull/426
The regexp for repo names is adjusted to support those separators.
```
regctl image copy $src localhost:5000/test---repo:latest
```
- Support multiple dashes in repo names.
=> Repo names may have multiple dashes

internal/reghttp/http.go
Copy to a repo where access is lacking results in backoffs before an eventual failure.
Auth errors should not trigger the backoff. These failures should be handled by callers. In the case of a copy, it's possible a registry could provide auth failures on the head/get requests before the repo is created by a push.
```
regctl image copy $src $dest
```
Where `$src` exists and `$dest` is a repo where push access does not exist.
- Fix: auth failures do not trigger a backoff
=> Auth failures should not trigger a backoff

types/warning/warning.go
Warning headers generate a bad log message.
This changes the log message field name to the string "warning".
google/go-containerregistry includes a warning header in 1% of requests.
Warning header log message is fixed.
=> Fix log from warning header messages

cmd/regctl/blob.go, types/blob/blob_test.go, types/blob/reader.go, types/blob/tar.go
On a partial tar read, closing the reader should not compare the digest. Fixes #502.
This moves the digest compare to only run after an EOF.
```
regctl image get-file alpine /etc/hosts
```
Fix digest check when running `regctl image get-file`
=> Only check digest on EOF

.github/workflows/docker.yml, build/oci-image.sh, scheme/ocidir/referrer_test.go, scheme/reg/referrer_test.go
Artifact annotations were removed from OCI release candidates and shouldn't be used.
This changes back to image annotations where appropriate, and example annotations in tests.
Generated `regclient/reg*` images should no longer have `org.opencontainers.artifact.*` annotations.
- Switch `org.opencontainers.artifact.*` to `org.opencontainers.image.*` annotations in regclient images.
=> Cleanup artifact annotations

cmd/regctl/root.go, cmd/regsync/config.go, cmd/regsync/regsync_test.go, cmd/regsync/root.go, docs/regsync.md, internal/cache/cache.go, internal/cache/cache_test.go, scheme/reg/manifest.go, scheme/reg/manifest_test.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go, scheme/reg/reg.go
This adds an optional cache of manifests and referrers. The manifests are only cached by digest. The cache has a fixed number of items and a timeout. `regctl` sets this to a 5 minute timeout and 500 items, neither of which are ever expected to be reached. `regsync` supports caching if `defaults.cacheCount` and `defaults.cacheTime` are set, which may speed up the copy of images with referrers that have multiple tags to the same manifest. Library users can use `regclient.WithCache` to enable caching.
Commands that would pull a manifest multiple times no longer do this. `regctl index create` with the same ref multiple times is one example.
- Add in memory caching support.
=> Add an in memory cache of manifests and referrers

internal/limitread/limitread.go, internal/limitread/limitread_test.go, internal/reghttp/http.go, internal/reghttp/http_test.go, scheme/reg/manifest.go, scheme/reg/manifest_test.go, scheme/reg/reg.go, types/blob/blob_test.go, types/blob/reader.go, types/blob/tar.go, types/error.go
OCI recommends a 4MB manifest limit that clients should avoid exceeding when creating new manifests.
- This adds a 4MB manifest put limit (per the OCI spec).
- It also adds an 8MB manifest get limit to prevent DOS attacks.
- Blob reads also stop when the expected length is reached.
- HTTP retry backoff checks were added to read/close methods.
A manifest put for a very large manifest should fail.
- Add size limits on manifests
=> Add manifest and blob get/put limits

cmd/regctl/artifact.go
The OCI guidance is changing to recommend new artifacts always set the `artifactType` field.
This adjusts the `regctl artifact put` command to set `artifactType` even if only the `--config-type` flag is passed.
```
echo '{"config": "test"}' >config.json
echo test | regctl artifact put --config-type application/vnd.example+json --config-file config.json ocidir://test:artifact
```
- Always set `artifactType` with `regctl artifact put`
=> Created artifacts should always set artifactType

build/oci-image.sh, cmd/regctl/artifact.go, scheme/ocidir/manifest.go
Running reproducible build script leaves stale referrers from previous builds.
- manifest delete should not fail when referrer file is missing
- artifact put of referrer should not add a manifest reference in ocidir
- reproducible image creation scripts should prune stale referrers
```
make oci-image
```
- Fix: manifest delete should not fail when referrer file is missing
- Fix: artifact put of referrer should not add a manifest reference in ocidir
- Fix: reproducible image creation scripts should prune stale referrers
=> Avoid and clean stale content in ocidir

image.go
Copy to a down target results in multiple retry tests for every manifest and blob.
The manifest head request to the target typically ignores errors since the target may not exist. This checks a resulting error for `*url.Error` that results from an HTTP connection failure.
```shell
regctl image copy $src localhost:12345/no-such-registry # where nothing is listening on 12345
```
- Fail faster on image copy when target registry is unreachable
=> Fail faster when target of copy is down

cmd/regctl/tag.go, scheme/ocidir/tag.go, types/tag/taglist.go
There is no way to access the nested contents of an OCI Index from the tag listing.
This stores the index and exposes it as `{{.Index}}`.
```shell
regctl tag ls ocidir://output/regctl --format '{{range $manifest := .Index.Manifests}}{{println $manifest.Digest}}{{end}}'
```
- Expose the underlying OCI Layout Index to `regctl tag ls --format`
=> Add the ability to access the OCI index in tag ls

cmd/regctl/image.go, image.go, image_test.go
Fixes #519
This adds support for compression on image import and export.
```shell
regctl image export --compress $ref $file.tgz
regctl image import $ref $file.tgz
```
- Support compression on image export and import.
=> Support compression on import and export

.github/workflows/docker.yml, build/oci-image.sh, cmd/regctl/image.go, cmd/regctl/image_test.go, mod/config.go, mod/dag.go, mod/layer.go, mod/mod.go, mod/mod_test.go, mod/time.go
Changing timestamps by a "max time" option is limited. It doesn't allow times to be moved forward. And it could conflict with base images, particularly after rebasing on a newer base image.
Make the image mod timestamp methods aware of base images and allow those to be excluded from updates. Then allow timestamps to be set to a specific value, which can adjust the time either forward or backwards.
Build of regclient reproducible images have been updated.
```shell
regctl image mod --help
```
- Image mod of timestamps is now aware of base images.
=> Make mod time aware of base images

.github/workflows/docker.yml, build/oci-image.sh, cmd/regctl/image.go, mod/layer.go, mod/mod_test.go
This currently reverts files back to numeric ids, fixing an issue seen in some image builders.
The reproducible build is broken depending on the local version of buildkit.
This adds a method to remove the username/groupname from the image layers, reverting to numeric ids.
```shell
make oci-image
```
- Add reproducible method / option to image mod.
=> Add a layer mod for reproducibility

.github/workflows/docker.yml, build/oci-image.sh, mod/dag.go, mod/manifest.go
The image mod is changing the contents of the Docker build attestation.
This refactors the process to use the embedded DAG. This also changes the image build to separate out the conversion since changes are made depth first and conversion of referrers runs on the parent node, so referrers will always be converted after the referrer manifest is changed.
```shell
make oci-image
```
- Avoid changing docker build attestations when converting to referrers
=> Refactoring mod of Docker to OCI referrers

cmd/regctl/image.go, mod/config.go, mod/mod_test.go
This allows labels to be set for specific platforms with `regctl image mod` by prefixing the label name with an array of platforms.
```shell
regctl image mod --label '[linux/amd64]key=value' $image --create mod
```
- Support setting labels on specific platforms with image mod.
=> Image mod: set labels for specific platforms

cmd/regctl/image.go, cmd/regctl/image_test.go, mod/layer.go, mod/mod_test.go
This replaces `WithFileTarTimeMax` with a version that recognizes base image layers, and has more options to setting the time.
```shell
regctl image mod --create ocidir:///tmp/regctl-test:mod \
--file-tar-time filename=dir/layer.tar,set=2020-01-01T12:00:00Z,base-ref=ocidir://testdata/testrepo:b1 \
ocidir://testdata/testrepo:v3
```
- Add `WithFileTarTime` method and `regctl image mod --file-tar-time` option to edit timestamps inside tar files.
=> Adds a WithFileTarTime method

cmd/regctl/artifact.go, cmd/regctl/artifact_test.go
This adds support for showing digest-tags (i.e. those used by sigstore) in the `regctl artifact list` and `regctl artifact tree` output.
```shell
regctl artifact list --platform local --digest-tags ghcr.io/regclient/regctl:edge
regctl artifact tree --digest-tags ghcr.io/regclient/regctl:edge
```
- Support digest-tags in artifact list and tree output
=> Support digest-tags in artifact list and tree

go.mod, go.sum, pkg/archive/compress.go
Add xz support for compression module, allowing import xz compressed tar file.
- Add support for decompressing xz layers
=> Add xz format support to compression.

cmd/regsync/config.go, cmd/regsync/regsync_test.go, cmd/regsync/root.go, docs/regsync.md
Fixes #533
This adds a `repos` filter similar to the `tags` filter when copying registries with regsync.
With a registry that supports the `_catalog` API, a regsync config like the following:
```yaml
sync:
- source: localreg:5000
target: localcopy:5000
type: registry
repos:
allow:
- "team-x\\/.*"
deny:
- ".*backup"
```
Would copy every repo under `team-x` excluding any repo name that ends in `backup`.
- Add repo filters to regsync when copying registries
Because `_catalog` is not supported on many registries, and not implemented with `ocidir`, tests are not yet available for this.
=> Add support for repo filters in regsync

types/blob/blob.go, types/blob/blob_test.go, types/blob/common.go, types/blob/ociconfig.go, types/blob/reader.go, types/blob/tar.go
The blob package contained several unnecessary interfaces.
Structs were exposed so they can be passed directly, with unexported variables and methods on each. To minimize the risk of breaking users, type aliases were used on the old interface names. Comments were updated to better align with the godoc style.
This is hopefully transparent to users.
- Refactor type/blob package.
- Breaking: a few interfaces in the blob package were converted to pointers to structs.
=> Refactoring the blob package

cmd/regctl/artifact.go, cmd/regctl/artifact_test.go
This allows artifacts to be pushed as entries to an index using the `regctl artifact put --index` flag.
```shell
$ echo oatmeal and orange juice \
| regctl artifact put --annotation meal=breakfast --platform linux/amd64 \
--artifact-type application/example.fbom --index ocidir://test/fbom:index
$ echo turkey sandwitch, bananna, and water \
| regctl artifact put --annotation meal=lunch --platform linux/arm64 \
--artifact-type application/example.fbom --index ocidir://test/fbom:index
$ regctl manifest get ocidir://test/fbom:index
Name:           ocidir://test/fbom:index
MediaType:      application/vnd.oci.image.index.v1+json
Digest:         sha256:95cb8dbe5267ac9ce1ea40dd2398771c46b6777a6981577e38a211fdfdb03c02
Manifests:      
Name: …
```
=> Support pushing artifact as index entry

cmd/regbot/main.go, cmd/regbot/regbot_test.go, cmd/regbot/root.go, cmd/regctl/artifact.go, cmd/regctl/artifact_test.go, cmd/regctl/blob.go, cmd/regctl/blob_test.go, cmd/regctl/completion.go, cmd/regctl/config.go, cmd/regctl/config_test.go, cmd/regctl/digest.go, cmd/regctl/image.go, cmd/regctl/image_test.go, cmd/regctl/index.go, cmd/regctl/index_test.go, cmd/regctl/main.go, cmd/regctl/main_test.go, cmd/regctl/manifest.go, cmd/regctl/manifest_test.go, cmd/regctl/registry.go, cmd/regctl/repo.go, cmd/regctl/root.go, cmd/regctl/tag.go, cmd/regctl/tag_test.go, cmd/regsync/main.go, cmd/regsync/regsync_test.go, cmd/regsync/root.go
Testing of cobra CLI's gets a bit complicated and error prone since all options are globals that can be modified by other tests.
Moves all initialization into setup functions that can be directly called.
Hopefully there are no user visible changes, but it's a significant refactoring so no promises.
- Chore: refactoring CLIs to remove global state.
=> Refactoring cobra commands to remove globals

docs/regctl.md
The new example uses a much simpler go-template syntax and also showcases a better use case: get the actual version for a latest tag:
```console
❯ docker run --rm regclient/regctl:v0.5.1 image inspect --format '{{index .Config.Labels "org.opencontainers.image.version"}}' regclient/regctl:latest
v0.5.2%
```
=> Improve "output a single label" example

cmd/regctl/image.go, cmd/regctl/image_test.go
Fixes #551 
Adds the image config as an anonymous field in the returned struct to allow better formatting options.
```shell
regctl image inspect regclient/regctl:latest --format '{{ jsonPretty .Config.Labels }}'
```
- Fix formatting variables in `regctl image inspect`.
=> Fix regression in formatted output of image config

Makefile
The `oci-image-%` target depends on `bin/regctl`, but doesn't actually use it. This patch prepends the `bin/` dir to `$PATH`, causing `build/oci-image.sh` to use the freshly built `regctl`.
=> Use newly built regctl in oci-image target

.github/workflows/docker.yml, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit
First, `SOURCE_DATE_EPOCH` was misspelled in the workflow file, so the vcs_sec value did not get passed in correctly.
Second, the fallback had a syntax error:
```
SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH}:-$(date +%s)}"
^
```
The accidental `}` meant that something like `:-1696222361}` would unconditionally get appended.  If `$SOURCE_DATE_EPOCH` was e.g. `1234567890`, it would get changed to `1234567890:-1696222361}`.
If it wasn't set to begin with, it would become `:-1696222361}`.
Third, the reason it works when `SOURCE_DATE_EPOCH` is passed in correctly is that the shell construct where `SOURCE_DATE_EPOCH` was to be used does not work as expected:
SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(date +%s)}" find . -exec touch --date="@${SOURCE_DATE_EPOCH}" '{}' \;
Setting `SOURCE_DATE_EPOCH` in …
=> Fix regbot reproducible build

types/manifest/docker1.go, types/manifest/docker2.go, types/manifest/manifest.go, types/manifest/manifest_test.go, types/manifest/oci1.go
Fixes #562 
This adds a `GetSize` method on the `Imager` interface used by images.
```shell
$ regctl manifest get --platform local regclient/regctl:alpine --format '{{.GetSize}}'
15674121
```
- Feature: Add a `GetSize` method to image manifests (OCI and Docker2 manifests).
=> Add GetSize method on images

cmd/regctl/root.go, docs/regctl.md, internal/strparse/strparse.go, internal/strparse/strparse_test.go
Fixes #552.
This adds a `regctl --host` flag allowing credentials to be passed for a single command.
E.g. `regctl --host 'reg=registry.example.org,user=joe,pass=Pa$$w0rd' image inspect registry.example.org/secret-project:tag`.
```shell
regctl --host 'reg=localhost:5000,tls=disabled repo ls localhost:5000
```
- Add `regctl --host` flag to configure registries for a single command.
Note: Tests were added for the contained `strparse` package, but not for `regctl` since that would require setting up a registry with authentication.
=> Add regctl --host flag

internal/reghttp/http.go, internal/reghttp/http_test.go, repo.go, repo_test.go, scheme/reg/reg.go, scheme/reg/repo_test.go
Fixes #575
The `regclient.RepoList` method does not validate inputs which could result in a crash. This resolves the underlying crash and adds a minimal sanity check on the RepoList hostname value.
Regsync with a config:
```yaml
sync:
- source: registry.example.org/path
target: destination.example.org/path
type: registry
```
Should now fail gracefully.
- Fix handling of invalid hostname in `regclient.RepoList`.
=> Fix crash on RepoList from invalid hostname

cmd/regsync/root.go
Fixes #576.
On the `regsync server` startup, a first pass is run to only copy missing tags before falling back to the scheduled updates. This quickly gets new tags, but in this case, the generation of the tag list to copy had a minor error that caused the unfiltered list to be used.
See linked issue.
- Fix bug in regsync tag filtering when running as a server.
=> regsync: fix tag filter on server first pass

mod/layer.go
We should use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` when matching string to avoid unnecessary `[]byte` conversions and reduce allocations.
Example benchmark:
```go
var re = regexp.MustCompile("^COPY layer2.txt /layer2")
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := re.Match([]byte("COPY layer2.txt /layer2")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := re.MatchString("COPY layer2.txt /layer2"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: github.com/regclient/regclient/mod
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 3593138	       487.0 ns/op	      24 B/op	       1 allocs/op
BenchmarkMatchString-16 …
```
=> mod/layer: avoid allocations with `(*regexp.Regexp).MatchString`

internal/auth/auth.go, internal/reghttp/http.go, internal/retryable/retryable.go
Unspecified timeouts on the HTTP client could result in indefinite delays for network issues.
Define HTTP client timeouts following the [guidance from cloudflare](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/).
Connecting to an IP that doesn't explicitly reject the connection (firewall drops the packets) should result in a few retries but no more than a 30 second delay for each connection attempt.
- Configure HTTP client timeouts.
Tests for connection failures are non-trivial to automate. This has been tested by hand.
=> Add timeouts to http clients

Makefile
Properly state the dependence between the binaries targets and vendor.
It prevent make parallel builds of the  "binaries" target (i.e. `make -j binaries`) to fail with errors `... is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt`
Re https://github.com/Homebrew/homebrew-core/pull/153571
`make -j binaries`
Enable parallel builds of the make "binaries" target.
=> Makefile: $(BINARIES) depends on "vendor"

cmd/regctl/registry.go, internal/auth/auth.go, internal/reghttp/http.go, ping.go, scheme/ocidir/ping.go, scheme/ocidir/ping_test.go, scheme/reg/ping.go, scheme/reg/ping_test.go, scheme/scheme.go, types/ping/ping.go
This extends #583 with the following:
- Adds a struct to the return so headers can be inspected.
- Puts Ping into the scheme interface.
- Adds an ocidir implementation to verify directory is accessible.
- Fixes some http/auth handling.                                                                     
- Warns on `regctl registry config` and `login` of Ping failure.
Bad configurations from:
```shell
regctl registry set ...
regctl registry login ...
```
will now output a warning.
- Add `regclient.Ping` method.
- regctl: warn on failed logins or bad registry configuration changes.
=> Add a Ping method

types/descriptor.go, types/descriptor_test.go
Fixes #593.
Adjust the field order to match the upstream OCI types.
Generating new JSON content will have digest before the size field. Note that JSON rendering of existing content is frequently passed through from the original source.
- Chore: reorder descriptor fields.
=> Align descriptor field order with OCI spec

internal/auth/auth.go, internal/reghttp/http.go, internal/retryable/retryable.go
This fixes proxy connections, limits idle connections, and uses HTTP2.
Fixes #614.
Rollback #584. Timeouts were already included in `http.DefaultTransport`:
```golang
var DefaultTransport RoundTripper = &Transport{
Proxy: ProxyFromEnvironment,
DialContext: defaultTransportDialContext(&net.Dialer{
Timeout:   30 * time.Second,
KeepAlive: 30 * time.Second,
}),
ForceAttemptHTTP2:     true,
MaxIdleConns:          100,
IdleConnTimeout:       90 * time.Second,
TLSHandshakeTimeout:   10 * time.Second,
ExpectContinueTimeout: 1 * time.Second,
}
```
Proxies defined with `http_proxy` and `https_proxy` should work again.
- Fix: HTTP proxy using environment variables.
=> Use http.Client default values

.version-bump.yml, go.mod
This project supports the last 3 major Go versions. Go itself only supports the last 2 major releases.
Projects that depend on this may be forced to upgrade prematurely.
This sets the version in the go.mod to the oldest supported release. The various commands built by the project are still using the latest release of Go.
- Chore: go.mod version is now set to oldest supported release.
=> Change go.mod version to oldest supported release

Makefile, build/Dockerfile.regbot, build/Dockerfile.regbot.buildkit, build/Dockerfile.regctl, build/Dockerfile.regctl.buildkit, build/Dockerfile.regsync, build/Dockerfile.regsync.buildkit
Replaces #589.
This removes the requirement to use a local vendor folder, but uses and maintains it if it exists.
```shell
make all docker
```
- Chore: Make vendoring optional.
=> Make vendoring optional

go.mod, go.sum, image_test.go
The `ImageCopy` tests previously depended on a setup that used `ImageCopy`. This leverages the capability of olareg to run a registry in memory that is backed by a directory for the initial content.
```shell
make test
```
- Chore: Update `ImageCopy` test to not depend on `ImageCopy` for setup.
=> Update olareg to leverage mem backed by dir

cmd/regctl/config_test.go, config/credhelper_test.go, config/docker_test.go, config/host_test.go, internal/conffile/conffile_test.go, mod/time_test.go
Tests that modify the environment run in parallel and manually reset values.
Leverage `t.Setenv` where possible.
```shell
make test
```
- Chore: leverage `t.Setenv` in tests of environment variables.
=> Use t.Setenv in tests

internal/reghttp/http.go, scheme/reg/blob.go, scheme/reg/blob_test.go, types/error.go
Fixes #621.
The blob put method depends on the input being an io.Seeker for retries. If that is not the case, abort and return the previous error.
- Fix: Improve error handling on blob put retries when source is not an io.Seeker.
=> Handle unretryable failures in http requests

scheme/reg/blob.go, scheme/reg/blob_test.go
This also adds special handling for the empty blob, and validates the descriptor.
Replaces #611
This both preserves the descriptor, but also validates it and better handles the zero length blob.
Tests have been added:
```
make test
```
- Fix: Preserve descriptor contents on chunked blob push. (@edigaryev)
- Fix: Validate descriptor contents on chunked blob push.
=> Preserve the descriptor on chunked blob put

cmd/regctl/registry.go, cmd/regctl/registry_test.go
Fixes #643 
This adds a `--skip-check` flag to `regctl registry set` and `regctl registry login` commands.
```shell
regctl registry set ... --skip-check
regctl registry logini ... --skip-check
```
- Add a `--skip-check` option to `regctl registry set` and `regctl registry login`.
=> Allow registry check to be skipped on set and login

cmd/regctl/artifact.go, cmd/regctl/artifact_test.go
The title annotation for filenames in artifacts attempted to mirror other projects but is an atypical usage of the annotation and not documented by OCI. It could also be used to accidentally leak data. This stops including it by default but allows it with a `regctl artifact put --file-title` option for those that need it.
```shell
regctl artifact put --artifact-type application/vnd.example --file ./some-file.txt localhost:5000/aritfact:test
```
- Breaking: `regctl artifact put` no longer includes the filename annotation by default. Use `--file-title` to include.
=> Make artifact filename annotation optional

cmd/regctl/artifact.go, cmd/regctl/blob.go, cmd/regctl/config.go, cmd/regctl/image.go, cmd/regctl/index.go, cmd/regctl/root.go, cmd/regctl/tag.go
Fixes #644
This adds examples to the help messages of the various `regctl` commands.
```shell
$ regctl --help
Utility for accessing docker registries
More details at https://github.com/regclient/regclient
Usage:
regctl [command]
Examples:
regctl registry login ghcr.io
regctl registry set --tls disabled registry.example.org
regctl image copy ghcr.io/regclient/regctl:latest registry.example.org/regctl:latest
regctl tag ls ghcr.io/regclient/regctl -v debug
regctl image ratelimit --logopt json alpine
regctl image digest --host reg=localhost:5000,tls=disabled localhost:5000/repo:v1
Available Commands:
artifact    manage artifacts
blob        manage image blobs/layers
completion  Generate completion script
config      read/set configuration options
help        Help about any command
image …
```
=> Add examples to regctl help messages

mod/dag.go, mod/manifest.go, mod/mod.go, mod/mod_test.go
Trying to rebase and copy an image with a `regctl image mod --rebase --create $tgt $src` would fail registry validation of the manifests because of missing blobs.
Multiple fixes were applied to the mod:
- Rebase should define a different source repository
- Referrers should only be updated in same repository
- Tests should use olareg for manifest validation
- Pushing manifest by digest should handle unchanged copy
```shell
regctl image mod --rebase \
--create localhost:5000/regclient/regctl:v0.5.1-alpine-rebase \
ghcr.io/regclient/regctl:v0.5.1-alpine
```
- Fix: Image mod where created image is in a different repository
=> Fixes for image mod to different target registry

image.go, image_test.go
A failed image copy, e.g. to a repo without write access, often returns a `context.Canceled` error rather than the http or other error.
This prefers errors other than the `context.Canceled` that is generated by stopping goroutines.
Copy from a source to a destination where you do not have write access:
```shell
regctl image copy busybox noaccess
```
- Fix: Improve returned errors from `regclient.ImageCopy`.
=> Improve error handling of a failed copy

blob_test.go, scheme/reg/blob.go, scheme/reg/blob_test.go
Failed blob uploads leave the in progress upload on the registry.
On a blob upload failure, this attempts to cancel the upload, ignoring any additional errors.
```shell
echo "hello" | regctl blob put localhost:5002/x --digest sha256:a8e1571c8aece39aa60cd64b3da4694b936887b620ad7e370b270fbdcca9afec -v debug
```
- Fix: Cancel blob uploads on failures.
=> Cancel failed blob uploads to a registry

cmd/regctl/blob.go, cmd/regctl/blob_test.go, scheme/ocidir/blob.go, scheme/ocidir/blob_test.go
This adds support for `BlobDelete` on an ocidir reference. And it adds the `regctl blob delete` CLI. This should typically not be used, in favor of letting the registry run a garbage collection. However, it may be useful for repairing a corrupt registry.
```shell
digest="$(echo "hello world" | regctl blob put localhost:5000/test)"
regctl blob get localhost:5000/test $digest
regctl blob delete localhost:5000/test $digest
regctl blob get localhost:5000/test $digest
```
- Feature: Add `BlobDelete` support for ocidir references.
- Feature: Add `regctl blob delete` command.
=> Add regctl blob delete and ocidir blob delete API

cmd/regctl/registry.go, cmd/regctl/registry_test.go
This adds the ability to format output from the `regctl registry config` command.
```shell
regctl registry config docker.io --format '{{.User}}'
```
- Feature: Support formatting output on `regctl registry config`.
=> Support formatted output on regctl registry config

cmd/regctl/image.go, mod/manifest.go, mod/mod_test.go
This allows common annotations to be copied to the index. The intended workflow is to individually label each image in the Dockerfile or as part of the build, copy those labels to annotations, and copy the image annotations to an index annotation.
```shell
regctl image mod --annotation-promote $src --create $tgt
```
- Feature: Add image mod ability to promote common annotations in the child images to the index.
=> Add image mod annotation promotion

mod/manifest.go, mod/mod_test.go
Promoting annotations doesn't work when also copying labels to annotations and converting docker referrers to OCI referrers. This is because the docker referrers do not have labels converted to annotations.
Ignore deleted child manifests when promoting annotations.
Scripts to build regclient images will be updated in a PR shortly that depend on this. This can be reproduced by building docker images for multiple platforms, with common labels, and Docker build provenance, and then running:
```shell
regctl image mod $image \
--to-oci-referrers --label-to-annotation --annotation-promote
```
- Fix: Promoting annotations should ignore child manifests that have been removed from the tree.
=> Handle deleted child manifests when promoting annotations

.github/workflows/docker.yml, build/oci-image.sh
The base image annotation may not match the base image digest pinned in the Dockerfiles.
Base image digest is pinned in Dockerfile, so it should not be pulled dynamically in scripts. Version bump scripts will be updated with the weekly version update.
```shell
make oci-image
```
- Fix: Pin base image digest in build scripts to match Dockerfile pins.
=> Pin base image digest in scripts

cmd/regctl/artifact.go, cmd/regctl/image.go, config/credhelper.go, internal/auth/auth.go, internal/reghttp/http.go, scheme/reg/blob.go, types/blob/reader.go
Some errors were not properly wrapped.
This fixed `%v` that should have been `%w`. And support for wrapping multiple errors is now available with 1.19 support being dropped, allowing `%w ... %w` in a format.
Change will be transparent to CLI users. Library users will be able to leverage `errors.Is` in more scenarios.
- Fix: Error wrapping fixed in several locations.
=> Fix wrapped errors

cmd/regctl/image.go, cmd/regctl/index.go, cmd/regctl/manifest.go, docs/README.md, types/descriptor/descriptor.go, types/platform/compare.go, types/platform/compare_test.go, types/platform/cpuinfo.go, types/platform/platform.go, types/platform/platform_other.go, types/platform/platform_test.go
Selecting a windows image with a different variant is not possible.
This is a refresh of the platform code to better support multiple variants (e.g. amd64 v2 and v3). Platform selection now prefers a best match rather than the first compatible match (when an exact match wasn't found).
Selecting windows OS version now depends on a comma separated key/value syntax `linux/amd64,osver=10.0.17763.4974`.
```shell
regctl manifest get golang --platform windows/amd64,osver=10.0.17763
```
- Breaking: The platform string for windows images no longer includes the non-standard OS Version value.
- Fix: Platform selection now finds the best match rather than the first compatible match.
- Feature: Specifying windows OS Version now uses a comma separated syntax in the platform string.
Because of the large …
=> Update platform parsing to support variants on more architectures

.version-bump.yml, Makefile, build/ci-test.sh, build/zot-config.json
CI tests for Zot are failing because the pinned RC tag no longer exists.
This updates the Zot version, removes some RC config settings in Zot, updates the distribution/distribution version, manages the versions with version-bump, and speeds up the tests.
```shell
make ci
```
- Fix: Update registry versions in CI tests.
=> Update Zot version for CI tests

Makefile, types/platform/cpuinfo.go, types/platform/cpuinfo_armx.go, types/platform/cpuinfo_other.go, types/platform/cpuinfo_x86.go, types/platform/cpuinfo_x86.s, types/platform/os_darwin.go, types/platform/os_other.go, types/platform/platform.go, types/platform/platform_other.go, types/platform/platform_windows.go
Update platform detection to support AMD64 variants.
Actions that lookup the local platform can now detect AMD64 v1-v4 variants in a manifest list. At present, this is rarely seen.
- Feature: Detect AMD64 variant when looking up local platform.
Testing is minimal since it depends on the local CPU.
=> Detect variant on amd64

cmd/regctl/image.go, mod/config.go, mod/mod_test.go
Fixes #690 
This adds the ability to set the platform in the image config.
```shell
regctl image mod --config-platform linux/amd64 $src --create amd64
```
- Feature: Add ability to set the config platform setting with `regctl image mod`.
=> Add image mod option to set config platform

cmd/regctl/image.go, mod/config.go, mod/mod.go, mod/mod_test.go
Fixes #532.
This adds the ability to set the endpoint and cmd in an image with `regctl image mod`.
```shell
regctl image mod registry.example.org/repo:v1 --create v1-bash \
--config-entrypoint '["bash"]' --config-cmd ""
```
- Feature: Image mod support for setting the entrypoint and cmd.
=> Add image mod options to set entrypoint and cmd

cmd/regctl/image.go, image.go, scheme/ocidir/manifest.go, scheme/ocidir/tag.go, scheme/reg/tag.go
Cleanup some unused parameters on private functions. Many of these were set to `_` to make it easier to reenable later. This is now flagged by gopls, but not yet in staticcheck.
In the editor, `gopls` errors for unused parameters should no longer appear.
- Chore: Cleanup unused parameters on private functions.
=> Chore: Cleanup unused params

.github/workflows/docker.yml
Docker Hub no longer blocks the push of images with a subject, so the SBOM push is reenabled. This also moves the signing step to the push to use the digest variable and skip signing of reproducible builds.
GHA should not fail, and on success, checking signatures and referrers should work:
```shell
regctl artifact list regclient/regctl:edge --platform linux/amd64
```
- Chore: Resume push of SBOMs to Docker Hub.
=> Update GHA registry push and sign steps

.github/workflows/vulnscans.yml, .osv-scanner.toml, .version-bump.yml, Makefile
OSV Scanner detects the Go version from the `go.mod` which is intentionally a few versions behind for library users.
Add a Go version override to inject the version used to build the binaries.
This also disables the scanner pending the next release upstream to support the override.
GHA will no longer fail the vulnerability scan.
- Fix: Override the Go version used by the OSV Scanner.
=> Override Go versions for OSV Scanner

cmd/regctl/artifact.go, cmd/regctl/artifact_test.go, types/mediatype/mediatype.go, types/mediatype/mediatype_test.go
It's possible with regctl to create artifacts with invalid media types in the artifact type, layers, and config descriptor.
This adds media type validation required by OCI, but only on the creation of artifacts with regctl. Trying to implement this at a lower level in regclient may break the ability to ingest and copy poorly formatted artifacts. This attempts to follow the robustness principle, conservative in what we generate, but liberal in what we accept from others.
```shell
echo hello | regctl artifact put --artifact-type broken localhost:5000/artifact:bad
```
- Fix: Validate media types on `regctl artifact put`.
=> Validate media types in created artifacts

cmd/regctl/image.go, cmd/regctl/manifest.go
The `--platform` option should be clear that it will trigger a GET request. Fixes #711.
This updates the `--help` output on `regctl image digest` and `regctl manifest head` to clarify the behavior of the flag.
```shell
regctl image digest --help
regctl manifest head --help
```
- Doc: Clarify `regctl manifest head --platform` will trigger a get request.
=> Document regctl manifest head --platform

scheme/reg/blob.go, scheme/reg/blob_test.go
Fixes #723 
When pulling a blob from a registry, the original descriptor should be used, and not only the digest. This makes future calls to return the descriptor correctly return the media type and any other associated fields.
```shell
regctl image copy alpine localhost:5000/library/alpine
regctl image mod --label test=label --create label localhost:5000/library/alpine
regctl manifest get --platform linux/amd64 localhost:5000/library/alpine:label
```
- Fix: Use the provided descriptor in the BlobGet/Head to a registry.
=> Use the full descriptor on a blob get response

cmd/regctl/image.go, mod/dag.go, mod/layer.go, mod/mod.go, mod/mod_test.go, pkg/archive/compress.go, types/mediatype/mediatype.go
Fixes: #719.
This adds the ability to change the layer compression with image mod. Note that zstd support needs to be added which will change this and a lot of other code. This currently supports changing between gzip and none.
```shell
regctl image mod $image --layer-compress none --create $tag
```
- Feature: Add ability to modify the layer compression.
=> feat: image mod layer compression

cmd/regbot/sandbox/image.go, cmd/regctl/image.go, go.mod, go.sum, image.go, image_test.go, mod/layer.go, mod/manifest.go, mod/mod.go, mod/mod_test.go, pkg/archive/compress.go, pkg/archive/compress_test.go, types/descriptor/descriptor.go, types/mediatype/mediatype.go
This adds support for zstd compressed layers. It can be used with `regctl image mod`, `regctl image get-file`, and similar commands.
```shell
regctl image mod alpine --create localhost:5000/library/alpine:zstd --layer-compress zstd --to-oci
regctl manifest get localhost:5000/library/alpine:zstd --platform linux/amd64
regctl image get-file localhost:5000/library/alpine:zstd /etc/alpine-release
```
- Feature: Add support for zstd compressed layers.
- Breaking: pkg/archive.Compress no longer decompresses the input.
=> Feat: Adding zstd support

cmd/regctl/image.go, cmd/regctl/image_test.go, docs/regctl.md
Fixes #722.
This adds a `regctl image create` command that outputs a scratch manifest and image config.
```shell
regctl image create localhost:5000/library/scratch
```
=> feat: Add regctl image create command

cmd/regctl/image.go, mod/dag.go, mod/layer.go, mod/mod_test.go, mod/time.go
Fixes #721.
This adds the ability to append a new layer from a tar file to an image. Note that the input must be a tar file, and by default it compresses the layer with gzip and uses the appropriate media type based on the manifest media type. It supports multi-platform images where the requested platforms are updated. The digest is computed on blob push which means the blob is always pushed to the registry even if the same tar is appended to multiple images (using `ocidir://` minimizes that overhead).
```shell
regctl image mod registry.example.org/repo:v1 --create v1-extended \
--layer-add "tar=file.tar,platform=linux/amd64"
```
- Feature: Add image mod ability to append layers to an image.
=> feat: image mod ability to add layers

cmd/regctl/root.go, cmd/regctl/root_test.go
Fixes #737.
Most of the code immediately returns when `ConfigLoadDefault` errors. For the one place that doesn't, it needs to initialize the config with a default value instead of leaving a nil pointer.
```shell
REGCTL_CONFIG=. regctl manifest get ghcr.io/regclient/regctl
```
- Fix: Handle nil pointer when config file is a directory.
=> Fix: Handle nil pointer when config file is a dir

cmd/regctl/image.go, cmd/regctl/image_test.go
Add the ability to append a layers to an image from a directory. This includes the contents of the directory, including timestamps and file ownership. However, it only includes files and directories, not symlinks or other special files.
```shell
regctl image mod registry.example.org/repo:v1 --create v1-extended \
--layer-add "dir=path/to/directory"
```
- Feat: regctl image mod add layer from directory.
=> Feat: regctl image mod add layer from directory

mod/mod.go, types/blob/blob_test.go, types/blob/reader.go
Fixes #745.
Avoid updating the `rdr` value until after `err` is checked since an interface to a `nil` value is not `nil`. This also hardens the blob reader to prevent panics on a `nil` value.
```shell
regctl -v error image mod fluent/fluent-bit:1.8 --layer-compress none --create ocidir://fluent-bit:1.8
```
followed by pressing `cont+c` to cancel the blob read.
- Fix: Prevent panic on interrupted image mod.
=> Handle nil blob reader

cmd/regctl/registry.go, cmd/regctl/registry_test.go
Fixes #750
On a `regctl registry set` or `regctl registry login`, return a non-zero if the registry ping fails. This is skipped when `--skip-check` is passed.
Perform `regctl registry set` to a non-existent registry, or `regctl registry login` with an invalid credential.
- Breaking: `regctl registry set` and `regctl registry login` will return a non-zero if the ping fails.
=> Feat: Return non-zero on a failed registry ping

tag_test.go
Enable deletion on olareg tests. While not needed yet, olareg has a breaking change to disable deletions by default in the next release.
```shell
make test
```
- Fix: Enable deletion on olareg tests
=> Fix: Enable deletion on olareg tests

types/ref/ref.go, types/ref/ref_test.go
https://github.com/bazel-contrib/rules_oci/issues/588
Allows `~` tilde in reference paths such as `ocidir://`, this needed because Bazel adds tildes to namespace dependencies. 
Added tests 
Allow `~` tilde in reference paths
=> feat: allow ~ (tilde) in reference paths

cmd/regctl/artifact.go, cmd/regctl/digest.go, cmd/regctl/image.go, image.go, internal/reghttp/http.go, internal/reqresp/reqresp.go, mod/config.go, mod/layer.go, mod/manifest.go, mod/mod.go, mod/mod_test.go, scheme/ocidir/blob.go, scheme/ocidir/manifest.go, scheme/reg/blob.go, scheme/reg/blob_test.go, scheme/reg/reg.go, types/blob/ociconfig.go, types/blob/reader.go, types/blob/tar.go, types/descriptor/descriptor.go, types/descriptor/descriptor_test.go, types/manifest/docker1.go, types/manifest/docker2.go, types/manifest/manifest.go, types/manifest/manifest_test.go, types/manifest/oci1.go
Other digest algorithms are not supported.
Support changing digest algorithm using methods in the descriptor. This also adds validation (to avoid panics from go-digest) and the ability to modify the digest (to make testing easier).
```shell
regctl image mod --digest-algo sha512 ocidir://path:tag --create sha512
regctl manfiest get ocidir://path:sha512
```
- Feature: Support digest algorithms beyond sha256.
- Feature: Support modifying the digest algorithm on an image.
- Fix: Validate digests before calling methods that could panic.
=> Support changing digest algorithm

scheme/reg/blob.go, scheme/reg/blob_test.go, scheme/reg/manifest.go, scheme/reg/manifest_test.go, scheme/reg/reg.go
When pushing a tagged manifest, an extra parameter is needed to change the digest algorithm from the registry default. This is needed if the manifest digest needs to be fixed to a non-canonical value to avoid breaking referrers, signatures, and pinned references.
These parameters are currently experimental and not standardized by OCI yet. This change will be part of a proposal to OCI, and changing the digest algorithm of images should not be done in a production environment at this time.
Push content with a different digest to the latest development release of olareg.
- Feature: Experimental support for pushing tagged manifests with different digest algorithms
=> Support pushing tagged manifests with different digest algorithms

.github/workflows/docker.yml
Remove docker build caching to GHA. This didn't increase the cache hit rate and ultimately slowed down the build. Most likely the GHA cache isn't large enough.
Builds should be faster with the same percentage of the cache hit.
- Chore: Remove docker build cache in GHA.
=> Remove docker build caching to GHA

types/platform/cpuinfo_x86.go, types/platform/platform.go, types/platform/platform_test.go
Using `--platform local` was not detecting amd64 variants correctly.
The `bitIsSet` function was returning the wrong value, forcing nodes to v1. This also adjusts the automatic appending of the variant to only happen when short values are provided. This avoids changing `linux/amd64` to `linux/amd64/vx` which would break existing users.
On an amd64 system that is at least v2:
```shell
regctl manifest get sudobmitch/demo:amd64-vx
regctl image digest sudobmitch/demo:amd64-vx --platform local
```
- Fix: Detect `amd64` variants for `--platform local`.
Tests are non-trivial to write for this since it is platform detection code that would run differently on different platforms.
=> Fix platform detection

config/docker.go, regclient.go
Make it easier to pull creds from a docker config.json outside of the standard location, without needing environmental variables. For example, a mounted K8s Secret of type `kubernetes.io/dockerconfigjson`.
`new feature`
This is a small nice-to-have, exposing existing functionality to `regclient` library users.
Connect to a registry using creds in a non-standard config file.
- Add a `WithDockerCredsFile() regclient.Opt`
- N/A - regclient doesn't have much coverage for opts, config.Docker tests reads
- will be picked up in godoc
=> Add WithDockerCredsFile() RegClient Opt

image.go, mod/layer.go, mod/mod_test.go
Fixes #786.
The correct path separator inside of a tar file is `/`. On Windows, the `filepath.Clean` is converting these to backslashes. This either removes the `filepath.Clean` where it's not needed, or adds a `filepath.ToSlash` to ensure the tar filename separator is always assumed to be a `/`.
Export an image on Windows.
- Fix: Tar path separator should always be a `/`.
Tests for this are difficult since they depend on Go's behavior on a Windows system.
=> Tar paths should use forward slashes

cmd/regctl/artifact.go, cmd/regctl/artifact_test.go
Fixes #791
The `regctl artifact get` command allows a config to be output to a file, but doesn't have an option to just show the config, and it still wants to return layers even when the config is saved. This adds a `--config` option to only return the config.
```shell
regctl artifact get --config ghcr.io/webassembly/wasi/http:0.2.0
```
- Feat: Add `regctl artifact get --config` option to only return the config.
=> Option to output config with regctl artifact get

scheme/reg/referrer.go, types/manifest/manifest.go, types/manifest/manifest_test.go
When pulling a pinned manifest, regclient should verify the provided pin and not the headers from the registry.
This prefers the user provided digest for the manifest over the registry header when it is available.
- Fix: Validate the digest of the ref when provided
=> Fix: Validate the digest of the ref when provided

.github/workflows/go.yml
Warning are output from GHA when performing a release.
Update GHA output generating steps. The old "echo ::set-output..." method was deprecated for writing to a file.
The next release should not output warnings for the "set-output" lines.
- Fix: Update GHA output generating steps.
=> Fix: Update GHA output generating steps

scheme/reg/referrer.go, scheme/reg/referrer_test.go
Some registries do not include the docker digest headers. This should support referrers listing by tag on those registries.
If a registry does not return the docker digest header in the manifest HEAD request, this adds a fallback to use a manifest GET request to retrieve the digest needed to lookup referrers.
```shell
make test
```
- Fix: Lookup referrers when registry does not give digest with head.
=> Fix: Lookup referrers when registry does not give digest with head

Makefile, cmd/regsync/root.go, mod/layer.go, types/descriptor/descriptor.go, types/manifest/docker2.go, types/manifest/oci1.go, types/referrer/referrer.go
Upgrading to Go 1.23.0 in development causes the build to fail because of staticcheck failures. This upgrades staticcheck to support 1.23 and then cleans up the new linter warnings.
- Chore: Update staticcheck and fix linter warnings for Go 1.23.
-
=> Chore: Update staticcheck and fix linter warnings for Go 1.23

blob.go, config/host.go, image.go, internal/pqueue/pqueue.go, internal/pqueue/pqueue_test.go, internal/reghttp/http.go, internal/reghttp/http_test.go, internal/reqmeta/data.go, internal/reqmeta/data_test.go, regclient.go, scheme/ocidir/blob.go, scheme/ocidir/ocidir.go, scheme/reg/blob.go, scheme/reg/manifest.go, scheme/reg/ping.go, scheme/reg/referrer.go, scheme/reg/reg.go, scheme/reg/repo.go, scheme/reg/tag.go, scheme/scheme.go
Copying images has a delayed start and regclient throttles itself even on a local network.
This is a significant refactor of the networking stack to remove the default rate limit and reorder the copy of layers to speed up the start of the copy and prioritize the copy of large layers to reduce the typical time to copy an image.
- Update scheme to use pqueue instead of throttle. This is a breaking change but library users are unlikely to encounter issues with the scheme change since both throttle and pqueue are internal packages, so it shouldn't be possible to call their methods directly or specify their types in variables.
- Remove multiple API support. This removes an undocumented API for deleting images from Hub. Users that depend on that functionality should consider a Docker Hub …
=> Refactor networking layer

internal/auth/auth.go, internal/auth/auth_test.go, internal/reghttp/http.go, internal/reghttp/http_test.go, scheme/reg/reg.go
Unable to access registries that require a login or anonymous token from behind a redirect.
A registry server that is just a redirect to a real server that requires auth will now work. Previously, auth was only sent to the first server, now it is only sent to the server that performed the auth. The auth package itself was also refactored a bit, removing unneeded interfaces and reducing exported fields.
```shell
regctl tag ls nabo.codimd.dev/hackmdio/hackmd
```
- Fix: Support auth on redirect.
=> Fix: Support auth on redirect

blob_test.go, cmd/regbot/regbot_test.go, cmd/regsync/regsync_test.go, image_test.go, manifest_test.go, mod/mod_test.go, tag_test.go
With the default requests per second setting removed, this override is no longer needed to speed up tests.
```shell
make test
```
- Chore: Remove `ReqPerSec` in tests.
=> Chore: Remove ReqPerSec in tests

blob.go, cmd/regctl/artifact.go, cmd/regctl/blob.go, cmd/regctl/image.go, cmd/regctl/index.go, cmd/regctl/manifest.go, image.go, manifest.go, scheme/reg/blob.go, scheme/reg/manifest.go, scheme/reg/referrer.go, scheme/reg/tag.go
Various requests return multiple warning messages if a registry outputs a warning header on every request.
When a registry returns a warning header on every request, clients should try to consolidate these.
Test with olareg:
```shell
olareg serve --store-type mem --warning "Ephemeral registry, content may be deleted"
```
Requests with `regctl` to that registry should return one warning per command.
- Feat: Consolidate warnings.
Testing this would need something monitoring stderr for every test, and enabling a registry with warnings on every test. For now, this is just a best effort.
=> Feat: Consolidate warnings

internal/reghttp/http.go, internal/reghttp/http_test.go, types/errs/error.go
Limit the number of retries for a request. The previous retry limits are only imposed at the registry level. This change prevents a single request from too many retries for various reasons, including flaky connections and logic loops in the code.
Configure a large number of mirrors and a small retry limit. Also, `make test`.
- Feat: Limit number of retries for a request.
=> Feat: Limit number of retries for a request

config/host.go, internal/reghttp/http.go, scheme/reg/reg.go
This removes the throttle from the `config`, putting it in `reghttp` where it is used. Ideally the config should only have static config values, but some methods for credential helpers are likely to remain.
This is transparent to anyone unless they accessed the `config` method directly.
- Chore: Move throttle from `config` to `reghttp`.
- Breaking: `config.Host.Throttle()` has been removed. Use `scheme.Throttler` instead.
=> Chore: Move throttle from config to reghttp

blob_test.go, types/blob/blob_test.go, types/blob/reader.go
It's possible for `regctl image copy` to panic from a data race.
Prevent data race when reading blob and seeking simultaneously. A seek to the current location is used to monitor the progress, making it possible for the callback to panic.
Testing with `-race` now has tests to detect this.
```shell
make test
```
- Fix: Prevent data race when reading blob and seeking.
=> Fix: Prevent data race when reading blob and seeking

cmd/regctl/config.go, cmd/regctl/config_test.go, cmd/regctl/root.go, config/host.go, config/host_test.go, config/testdata/docker-credential-test, regclient.go, regclient_test.go, scheme/reg/reg.go
Fixes #802.
This adds support for a default host config in regclient. In `regctl`, this exposes a flag to set the default credential helper, however additional options can be directly edited in the config file.
```shell
regctl config set --default-cred-helper "some-helper"
regctl tag ls $registry
```
- Feat: Add default host config.
=> Feat: Add default host config

cmd/regctl/blob.go, pkg/archive/tar.go
Detect integer overflows on type conversion. This removes a few gosec overrides.
```shell
make lint-gosec
```
- Fix: Detect integer overflows on type conversion.
=> Fix: Detect integer overflows on type conversion

internal/pqueue/pqueue_test.go
Race condition discovered in pqueue_test.go in recent GHA run.
Fix ordering of channel to release next step of the test to run after queue is freed, and avoid nil pointer deref.
- Fix: Race condition in the pqueue tests.
=> Fix: Race condition in the pqueue tests

Makefile, internal/retryable/error.go, internal/retryable/retryable.go, regclient/blob/blob.go, regclient/config.go, regclient/config/host.go, regclient/error.go, regclient/manifest/manifest.go, regclient/mediatype.go, regclient/regclient.go, regclient/template.go, regclient/types/error.go, regclient/types/mediatype.go, regclient/types/ratelimit.go, regclient/types/ref.go, regclient/types/types.go
This is a prerequisite for #749.
This switches the default build tag from `!nolegacy` to `legacy` so the packages are disabled by default. Legacy packages may still be used with `-tags legacy` added to the build. However, they may be permanently removed in a future release, and migrating to the newer packages is recommended.
No changes should be visible for users that have moved off of deprecated packages.
- Breaking: Disable legacy packages by default.
=> Breaking: Disable legacy packages by default

cmd/regsync/root.go, internal/sloghandle/logrus.go, internal/sloghandle/logrus_test.go, regclient.go, regclient_nowasm.go, scheme/ocidir/ocidir.go, scheme/ocidir/ocidir_nowasm.go, scheme/reg/reg.go, scheme/reg/reg_nowasm.go
Fixes #749.
This is the last part of the changes to move from logrus to slog. wasm binaries will now compile. Note that the project does not explicitly support wasm since it requires filesystem and network access typically blocked by the wasm sandbox.
```shell
GOOS=wasip1 GOARCH=wasm go build -o bin/regctl.wasm ./cmd/regctl/
```
- Feat: Move logrus calls into files excluded by wasm.
=> Feat: Move logrus calls into files excluded by wasm

types/ref/ref.go, types/ref/ref_test.go
Fixes #855.
This adds a plus to the list of allowed path characters in an OCI Layout reference.
```shell
regctl image copy ocidir://output/regctl:scratch ocidir://test/path+with+plus:latest
```
- Feat: Allow plus in ocidir path.
=> Feat: Allow plus in ocidir path

cmd/regctl/artifact.go, referrer.go, referrer_test.go, scheme/ocidir/referrer.go, scheme/reg/referrer.go, scheme/scheme.go, types/referrer/referrer.go, types/referrer/referrer_test.go
Include the source in the referrers response when the referrers are pulled from a location other than the subject repository. This simplifies handling external sources.
```shell
$ echo "Alpine Linux" | regctl artifact put --subject alpine ocidir://test/external:alpine-info --artifact-type application/example.contents
$ regctl artifact list alpine --external ocidir://test/external
Subject:        docker.io/library/alpine@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a
Source:         ocidir://test/external
Referrers:
Name:         ocidir://test/external@sha256:5f685e999e50aecd719512de9443c9bac27f60056580f6c3bdaf18d75c1c9ab3
Digest:       sha256:5f685e999e50aecd719512de9443c9bac27f60056580f6c3bdaf18d75c1c9ab3
MediaType:    application/vnd.oci.image.manifest.v1+json …
```
=> Feat: Include source in referrers response

cmd/regctl/artifact.go, cmd/regctl/artifact_test.go
This adds a `--external` flag to `regctl artifact put`, aligning it with other `regctl artifact` commands.
```shell
echo "hello external artifact" | regctl artifact put --subject alpine --external ocidir://test/external --artifact-type applicaiton/example.test 
```
- Feat: Add external flag to regctl artifact put.
=> Feat: Add external flag to regctl artifact put

cmd/regctl/image.go, cmd/regctl/image_test.go, image.go, image_test.go
Add the ability to copy images with external source and/or target referrer repositories.
```shell
echo "hello external artifact" | regctl artifact put --subject alpine --external ocidir://test/external --artifact-type application/example.test
regctl image copy alpine localhost:5002/library/alpine --referrers --referrers-src ocidir://test/external --referrers-tgt localhost:5002/external
```
- Feat: Copy image with external referrers.
=> Feat: Copy image with external referrers

types/platform/platform_test.go
Fixes #876. 
Fix the platform test for darwin/macos. Variant is only added automatically to platform splits with a single field (e.g. `macos`, `darwin`, or `amd64`).
The following should succeed on MacOS systems:
```shell
go test ./types/platform
```
- Fix: Platform test for darwin/macos should not add variant.
=> Fix: Platform test for darwin/macos should not add variant

scheme/ocidir/manifest.go, scheme/ocidir/referrer.go, scheme/ocidir/referrer_test.go, scheme/reg/manifest.go, scheme/reg/referrer.go, scheme/reg/referrer_test.go
While the descriptor requires a size and media type, the referrer API does not. This makes regclient more tolerant of non-conformant implementations by only requiring the digest to consume the subject field.
```shell
go test ./scheme/...
```
- Feat: Support incomplete subject descriptor.
=> Feat: Support incomplete subject descriptor

.version-bump.lock, Makefile, go.mod, go.sum
Version bump:
- davidanson/markdownlint-cli2 to v0.17.1
- golang.org/x/sys to v0.29.0
- golang.org/x/term to v0.28.0
=> Version bump

internal/auth/auth.go, internal/auth/auth_test.go, internal/reghttp/http_test.go
Fixes #865.
This removes an auth hop that was defaulting to a POST even when a refresh token isn't available, where many token servers do not support the POST. In the GET for a token, the request for an offline refresh token is removed. Requesting a new token will send the original credentials again rather than the refresh token. This improves compatibility with broken auth token servers.
Tests have been updated, and trace logs should show auth going directly to the GET request.
- Fix: Do not request offline refresh token.
=> Fix: Do not request offline refresh token

config/docker.go, config/docker_test.go, config/testdata/config.json
The docker config may contain auth entries that are not registries. This ignores those entries rather than attempting to parse them.
Tests have been added. Including an entry for `example.org/foo` in `~/.docker/config.json` will no longer modify the host config for `example.org`.
- Fix: Ignore unsupported entries in docker config.
=> Fix: Ignore unsupported entries in docker config

internal/auth/auth.go, internal/auth/auth_test.go
This fix addresses bearer token authorization because some registries return a "delete" action in their scope for deletions. The issue occurs in the following scenario: after calling GetManifest, a scope like "repository:reponame:pull" is added to the bearerHandler's scopes slice.
When DeleteManifest is called next, a new scope like "repository:reponame:delete" is added separately to the bearerHandler's scopes slice. This results in a request to the registry structured as "https://exampleurl?scope=repository:reponame:pull&scope=repository:reponame:delete". In this case, some registries may only return the token for the push action, causing an unauthorized error.
To fix this, instead of adding the "repository:reponame:delete" scope separately, we should prepend it to the scope for the same …
=> Fix addScope in bearerHandler

cmd/regbot/config.go, cmd/regbot/regbot_test.go, cmd/regbot/testdata/config1.yml, cmd/regbot/testdata/config2.yml, cmd/regsync/config.go, cmd/regsync/regsync_test.go, cmd/regsync/testdata/config1.yml, cmd/regsync/testdata/config2.yml
This affects both regbot and regsync where setting a default schedule would override a sync/script specific interval.
This only sets the schedule to a default value when a sync/script specific interval is not defined.
```shell
make test
```
- Fix: Interval overrides a default schedule in regsync and regbot.
=> Fix: Interval overrides a default schedule in regsync and regbot

cmd/regctl/registry.go, config/credhelper.go, config/credhelper_test.go, config/docker.go, config/docker_test.go, config/host.go, config/testdata/config.json, config/testdata/docker-credential-teststore
Warnings for changing registry configurations are still returned in some scenarios.
The previous fix only validated registry names in the auths section of the docker config. This also validates names listed in the credential helper or returned from the credential store.
Run `regctl` commands with a `~/.docker/config.json` that lists non-registry entries in the credential helpers or are returned from the credential store. Warnings for those entries should no longer be displayed.
- Fix: Validate registry names.
=> Fix: Validate registry names

cmd/regctl/registry.go, cmd/regctl/registry_test.go, types/errs/error.go
This adds the command:
```shell
regctl registry whoami
```
which returns the current logged in user, if configured. It also updates `regctl registry config` to call the credential helper to set the username in `regctl registry config`.
```shell
regctl registry whoami
regctl registry whoami ghcr.io
```
- Feat: Adding a whoami command.
=> Feat: Adding a whoami command

cmd/regctl/image.go, cmd/regctl/image_test.go, cmd/regctl/main.go, cmd/regctl/main_test.go, cmd/regctl/root.go
The new output makes it more apparent when the base image has changed to casual users. Tests were added, which required some work to pass through `regclient.Opts`. The empty error message is also suppressed to avoid an extra linefeed to stderr.
```shell
regctl image check-base ghcr.io/regclient/regctl:alpine
if ! regctl image check-base ghcr.io/regclient/regctl:alpine --quiet; then
echo build a new image here
fi
```
- Feat: Improve `regctl image check-base` output.
=> Feat: Improve regctl image check-base output

cmd/regsync/regsync_test.go, cmd/regsync/root.go
Fixes #922.
Add a regsync option to abort on errors. This stops regsync from retrying with backoffs when a registry is failing. Multiple errors are also joined using "errors.Join". Errors from the canceled context are not propagated up.
Use `--abort-on-error` on a failing registry, e.g. a registry without write access due to auth or or being in read-only mode.
```shell
regsync once --abort-on-error --config regsync.yml
```
- Feat: regsync option to abort on errors.
=> Feat: regsync option to abort on errors

cmd/regctl/manifest.go, cmd/regctl/manifest_test.go, cmd/regctl/tag.go, cmd/regctl/tag_test.go
Fixes #928.
Add a flag to `regctl tag rm` and `regctl manifest rm` to ignore a missing image if the delete API fails.
```shell
regctl tag rm registry.example.org/repo:missing
```
- Feat: regctl flag to ignore missing images on delete.
=> Feat: regctl flag to ignore missing images on delete

internal/auth/auth.go, internal/auth/auth_test.go
Fixes a panic when quotes are seen around the auth type
In addition to fixing the panic, this:
- Rewrites parser with a separate element and syntax states to make it easier to parse quoted and escaped strings
- Switches to the non-deprecated error vars
- Adds fuzz testing and more tests
No user visible changes on well behaved registries.
- Fix: Auth header parsing.
=> Fix: Auth header parsing

build/reproduce.sh
This adds a script that takes a given image and verifies it can be reproduced by rebuilding the given git commit. It is a bit slow since caching is disabled, and both images (scratch and alpine) are built as part of a reproducible build, and artifacts (SBOMs) are included in the build.
```shell
./build/reproduce.sh ghcr.io/regclient/regctl:v0.8.1
```
- Feat: Add a script to reproduce regclient images.
A separate doc PR will be made to the website.
=> Feat: Add a script to reproduce regclient images

internal/reghttp/http.go, internal/reghttp/http_test.go
N/A (I didn't create a separate issue)
Adds a `ns` query param to registry mirror requests. This matches the behavior of Containerd's own [Registry Host Namespace](https://github.com/containerd/containerd/blob/main/docs/hosts.md#registry-host-namespace) implementation, and has become a common convention in registry-server implementations providing mirror functionality.
Perform a registry request against a configured mirror (where the host does not match the namespace), and verify that the request includes the `ns` query parameter corresponding to the namespace.
- Add "ns" query param to registry mirror requests.
=> add "ns" query param to registry mirror requests

cmd/regbot/root.go, cmd/regctl/root.go, cmd/regsync/root.go
This makes the version output consistent between commands.
The `.dockerignore` causes all docker builds to be marked as "dirty" even when there are no changes to the repo.
- Chore: Cleanup version output.
=> Chore: Cleanup version output

config/docker.go, config/docker_test.go, config/testdata/docker-credential-test
This directly injects the docker config credentials using an environment variable instead of a config file. See https://github.com/docker/cli/pull/6008 for the upstream project change.
```shell
docker run -e DOCKER_AUTH_CONFIG="$(cat ~/.docker/config.json)" regclient/regctl manifest get $image -v trace
```
Note the registries processed in the debug logs.
- Feat: Support DOCKER_AUTH_CONFIG variable.
Documentation additions could be added to the regclient.org site in a separate PR.
=> Feat: Support DOCKER_AUTH_CONFIG variable
